"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type RequestRow = { id: string; direction: "incoming" | "outgoing"; source: { displayName: string }; target: { displayName: string }; reason: string; channels: string[]; contextType: string | null; contextId: string | null; status: string; expiresAt: string | null; deferredUntil: string | null; createdAt: string; updatedAt: string };
const labels: Record<string, string> = { PENDING: "En attente", ACCEPTED: "Acceptée", REFUSED: "Refusée", DEFERRED: "Reportée", CANCELLED: "Annulée", EXPIRED: "Expirée" };
export function ContactRequestsPanel({ incoming, outgoing }: { incoming: RequestRow[]; outgoing: RequestRow[] }) { const router = useRouter(); const [tab, setTab] = useState<"incoming" | "outgoing">("incoming"); const [busy, setBusy] = useState<string | null>(null); const [feedback, setFeedback] = useState(""); const rows = tab === "incoming" ? incoming : outgoing;
  async function mutate(row: RequestRow, action: string) { if (busy) return; if (action === "accept" && !window.confirm("Accepter enregistre votre accord pour cette demande. Aucun contact, message, appel ou accès n’est encore créé.")) return; if (["refuse", "cancel"].includes(action) && !window.confirm("Confirmer cette décision ? Aucun effet annexe ne sera déclenché.")) return; let deferredUntil: string | undefined; if (action === "defer") { deferredUntil = window.prompt("Date de reprise (entre 1 et 30 jours, format AAAA-MM-JJ)") ?? undefined; if (!deferredUntil) return; deferredUntil = new Date(`${deferredUntil}T12:00:00.000Z`).toISOString(); }
    setBusy(row.id); setFeedback(""); try { const response = await fetch(`/api/directory/contact-requests/${encodeURIComponent(row.id)}/${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expectedUpdatedAt: row.updatedAt, ...(deferredUntil ? { deferredUntil } : {}) }) }); if (!response.ok) throw new Error(response.status === 410 ? "Cette demande a expiré." : response.status === 409 ? "La demande a changé ou cette transition n’est plus possible." : "Action impossible."); setFeedback("Décision enregistrée. Aucun contact ni canal n’a été créé."); router.refresh(); } catch (error) { setFeedback(error instanceof Error ? error.message : "Une erreur est survenue."); } finally { setBusy(null); }
  }
  return <section aria-labelledby="pending-requests-title" className="rounded-2xl border bg-white p-5 shadow-sm"><h2 id="pending-requests-title" className="text-lg font-semibold text-slate-950">Demandes</h2><div role="tablist" className="mt-4 flex gap-2"><button role="tab" aria-selected={tab === "incoming"} onClick={() => setTab("incoming")} className="rounded-lg border px-3 py-2 text-sm font-semibold">Reçues</button><button role="tab" aria-selected={tab === "outgoing"} onClick={() => setTab("outgoing")} className="rounded-lg border px-3 py-2 text-sm font-semibold">Envoyées</button></div>
    {feedback ? <p role="status" className="mt-3 rounded-lg bg-slate-100 p-3 text-sm">{feedback}</p> : null}{rows.length ? <ul className="mt-4 space-y-4">{rows.map((row) => <li key={row.id} className="rounded-xl border p-4"><p className="font-semibold">{tab === "incoming" ? `${row.source.displayName} → ${row.target.displayName}` : `${row.source.displayName} → ${row.target.displayName}`}</p><p className="mt-2 whitespace-pre-wrap text-sm">{row.reason}</p><p className="mt-2 text-xs text-slate-600">Canaux : {row.channels.join(", ")} · {labels[row.status]} · créée le {new Date(row.createdAt).toLocaleDateString("fr-FR")}</p>{row.contextType ? <p className="mt-1 text-xs text-slate-600">Contexte : {row.contextType}{row.contextId ? ` — ${row.contextId}` : ""}</p> : null}<div className="mt-3 flex flex-wrap gap-2">{tab === "incoming" && row.status === "PENDING" ? <>{["accept", "refuse", "defer"].map((action) => <button disabled={busy === row.id} onClick={() => mutate(row, action)} key={action} className="rounded-lg border px-3 py-1 text-sm">{{ accept: "Accepter", refuse: "Refuser", defer: "Reporter" }[action]}</button>)}</> : null}{tab === "incoming" && row.status === "DEFERRED" ? <button disabled={busy === row.id} onClick={() => mutate(row, "resume")} className="rounded-lg border px-3 py-1 text-sm">Reprendre</button> : null}{tab === "outgoing" && ["PENDING", "DEFERRED"].includes(row.status) ? <button disabled={busy === row.id} onClick={() => mutate(row, "cancel")} className="rounded-lg border px-3 py-1 text-sm">Annuler</button> : null}</div>{row.status === "ACCEPTED" ? <p className="mt-3 text-xs font-semibold text-emerald-800">Accord enregistré : ceci n’est pas encore un contact.</p> : null}</li>)}</ul> : <p className="mt-4 text-sm text-slate-600">Aucune demande {tab === "incoming" ? "reçue" : "envoyée"}.</p>}</section>;
}
