"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";

export type ContactRow = { id: string; localRepresentation: { id: string; displayName: string }; remoteRepresentation: { id: string; displayName: string; type: string; title: string | null; organizationName: string | null; territory: string | null; description: string | null; relationshipPolicy: string }; source: { kind: "ACCEPTED_CONTACT_REQUEST"; requestId: string }; status: "ACTIVE" | "ARCHIVED" | "REVOKED"; createdAt: string; updatedAt: string; archivedAt: string | null };
const typeLabels: Record<string, string> = { PROFESSIONAL: "Professionnel", ORGANIZATION_REPRESENTATIVE: "Représentant d’une organisation", ASSOCIATION: "Association", PRIVATE: "Privé", OTHER: "Autre" };
const policyLabels: Record<string, string> = { OPEN: "Ouvert", MESSAGE_ONLY: "Messagerie uniquement", CLOSED: "Fermé" };

export function MyContactsPanel({ contacts: contactProps }: { contacts: ContactRow[] }) {
  const router = useRouter(); const feedbackRef = useRef<HTMLParagraphElement>(null); const [contacts, setContacts] = useState(contactProps); const [busy, setBusy] = useState<string | null>(null); const [feedback, setFeedback] = useState("");
  useEffect(() => setContacts(contactProps), [contactProps]);
  async function mutate(contact: ContactRow, action: "archive" | "restore") { if (busy) return; if (!window.confirm(action === "archive" ? "Archiver ce contact uniquement dans votre liste ? L’autre partie conservera sa fiche." : "Restaurer ce contact dans votre liste active ?")) return; setBusy(contact.id); setFeedback("");
    try { const response = await fetch(`/api/directory/contacts/${encodeURIComponent(contact.id)}/${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expectedUpdatedAt: contact.updatedAt }) }); const payload = await response.json(); if (!response.ok || !payload.contact?.id) throw new Error(response.status === 409 ? "Ce contact a changé. Actualisez avant de recommencer." : "L’action n’a pas pu être enregistrée."); setContacts((items) => items.map((item) => item.id === contact.id ? payload.contact : item)); setFeedback(action === "archive" ? "Le contact a été archivé uniquement dans votre liste." : "Le contact a été restauré dans votre liste."); router.refresh(); window.setTimeout(() => feedbackRef.current?.focus(), 0); } catch (error) { setFeedback(error instanceof Error ? error.message : "Une erreur technique est survenue."); window.setTimeout(() => feedbackRef.current?.focus(), 0); } finally { setBusy(null); } }
  return <section id="my-contacts" aria-labelledby="my-contacts-title" className="rounded-2xl border bg-white p-5 shadow-sm md:col-span-2"><h2 id="my-contacts-title" className="text-xl font-semibold text-slate-950">Mes contacts</h2><p className="mt-2 text-sm text-slate-600">Chaque contact provient d’une demande acceptée puis d’une confirmation humaine explicite. Aucun canal ni aucune coordonnée n’est ajouté.</p>{feedback ? <p ref={feedbackRef} tabIndex={-1} role="status" aria-live="polite" className="mt-4 rounded-lg bg-slate-100 p-3 text-sm outline-none">{feedback}</p> : null}
    {contacts.length ? <ul className="mt-5 grid gap-4 lg:grid-cols-2">{contacts.map((contact) => <li key={contact.id} className="rounded-xl border p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{typeLabels[contact.remoteRepresentation.type] ?? contact.remoteRepresentation.type}</p><h3 className="mt-1 text-lg font-semibold">{contact.remoteRepresentation.displayName}</h3><dl className="mt-3 space-y-2 text-sm"><div><dt className="font-semibold">Votre représentation concernée</dt><dd>{contact.localRepresentation.displayName}</dd></div>{contact.remoteRepresentation.title ? <div><dt className="font-semibold">Titre</dt><dd>{contact.remoteRepresentation.title}</dd></div> : null}{contact.remoteRepresentation.organizationName ? <div><dt className="font-semibold">Organisation</dt><dd>{contact.remoteRepresentation.organizationName}</dd></div> : null}{contact.remoteRepresentation.territory ? <div><dt className="font-semibold">Territoire</dt><dd>{contact.remoteRepresentation.territory}</dd></div> : null}<div><dt className="font-semibold">Politique lors de la création</dt><dd>{policyLabels[contact.remoteRepresentation.relationshipPolicy] ?? contact.remoteRepresentation.relationshipPolicy}</dd></div><div><dt className="font-semibold">Créé le</dt><dd>{new Date(contact.createdAt).toLocaleDateString("fr-FR")}</dd></div><div><dt className="font-semibold">Statut local</dt><dd>{contact.status === "ACTIVE" ? "Actif" : contact.status === "ARCHIVED" ? "Archivé" : "Révoqué"}</dd></div></dl><div className="mt-4">{contact.status === "ACTIVE" ? <button disabled={busy === contact.id} onClick={() => mutate(contact, "archive")} className="rounded-lg border px-3 py-2 text-sm font-semibold">Archiver ce contact</button> : contact.status === "ARCHIVED" ? <button disabled={busy === contact.id} onClick={() => mutate(contact, "restore")} className="rounded-lg border px-3 py-2 text-sm font-semibold">Restaurer ce contact</button> : null}</div></li>)}</ul> : <p className="mt-5 rounded-xl border border-dashed p-6 text-center text-sm text-slate-700">Aucun contact n’a encore été créé à partir d’une demande acceptée.</p>}
  </section>;
}
