ALTER TYPE "GovernedJourneyEventType" ADD VALUE IF NOT EXISTS 'ACTIVATED';
ALTER TYPE "GovernedJourneyEventType" ADD VALUE IF NOT EXISTS 'SUSPENDED';
ALTER TYPE "GovernedJourneyEventType" ADD VALUE IF NOT EXISTS 'RESUMED';
ALTER TYPE "GovernedJourneyEventType" ADD VALUE IF NOT EXISTS 'CLOSED';
ALTER TYPE "GovernedJourneyEventType" ADD VALUE IF NOT EXISTS 'CANCELLED';
