import type { CompassStep } from "./boussole-context.ts";
import type { BoussoleSequence } from "./boussole-dashboard.ts";
type Options = { glossary?: string[]; states?: string[] };
const step = (id: string, targetId: string, title: string, body: string, options: Options = {}): CompassStep => ({ id, targetId, title, body, detailedBody: body, targetStates: options.states, glossaryTermIds: options.glossary ?? [], animation: { focus: "outline", movement: "scroll-center", narration: body, subtitles: body, duration: 7, transition: "soft-focus", tryNow: true } });

export const newGovernedJourneySequences: BoussoleSequence[] = [
  { id: "choose-governed-format", title: "Choisir le bon format", description: "Comprendre le rôle du parcours gouverné avant de commencer.", steps: [
    step("new-governed-overview", "governed-journey-builder-overview", "Comprendre le parcours gouverné", "Un parcours gouverné structure une situation impliquant plusieurs acteurs, étapes, documents ou décisions. Sa création prépare un brouillon et ouvre son cockpit, sans contacter personne.", { glossary: ["parcours-gouverne", "gouvernance"] }),
    step("new-governed-vs-simple", "governed-journey-vs-simple-link", "Lien simple ou parcours gouverné ?", "Utilisez un lien simple pour collecter rapidement des informations. Utilisez un parcours gouverné lorsque la situation doit être organisée et suivie dans le temps.", { glossary: ["lien-simple", "parcours-gouverne"] }),
    step("new-governed-human", "governed-journey-human-governance-notice", "Gouvernance humaine", "Goodissima prépare la structure. Les décisions, invitations, accès et revues restent humains.", { glossary: ["gouvernance", "validation-humaine"] }),
  ] },
  { id: "use-journey-assistant", title: "Utiliser l’assistance", description: "Décrire le besoin et demander une proposition sans création automatique.", steps: [
    step("new-governed-ai", "governed-journey-ai-assistant", "Assistant de parcours", "L’assistant peut proposer un cadrage à partir de votre besoin. Il ne crée pas le parcours et ne valide aucune proposition automatiquement.", { glossary: ["intelligence-artificielle", "assistant-de-parcours", "validation-humaine"] }),
    step("new-governed-ai-need", "governed-journey-ai-need", "Décrire le besoin", "Décrivez clairement l’objectif et le contexte, sans donnée sensible inutile. Aucun champ n’est rempli par la Boussole.", { glossary: ["objectif", "contexte"] }),
    step("new-governed-ai-workspace", "governed-journey-ai-workspace", "Choisir ou nommer un Workspace", "Vous pouvez sélectionner un Workspace existant ou saisir le nom d’un nouvel espace. Le rattachement n’ouvre aucun accès et n’envoie aucune invitation.", { glossary: ["workspace", "rattachement-manuel"] }),
    step("new-governed-generate", "generate-governed-journey-proposal", "Générer une proposition", "Cette action appelle l’assistance pour préparer une proposition éditable. « Montrer la zone » ne lance aucun appel et ne modifie aucun champ.", { glossary: ["assistant-de-parcours", "proposition", "validation-humaine"] }),
  ] },
  { id: "review-journey-proposal", title: "Examiner la proposition", description: "Relire et corriger chaque élément réellement proposé.", steps: [
    step("new-governed-proposal", "governed-journey-proposal", "Proposition à valider", "Cette carte rassemble le cadrage proposé. Elle n’apparaît qu’après une génération réussie ou une proposition locale de secours.", { glossary: ["proposition", "validation-humaine"] }),
    step("new-governed-title", "governed-journey-title", "Nom du parcours", "Donnez un nom court permettant d’identifier immédiatement la situation.", { glossary: ["parcours-gouverne"] }),
    step("new-governed-objective", "governed-journey-objective", "Objectif", "Décrivez le résultat attendu à la fin du parcours.", { glossary: ["objectif", "resultat-attendu"] }),
    step("new-governed-participants", "governed-journey-participants-section", "Participants pressentis", "Relisez les personnes ou rôles proposés. Leur présence dans ce brouillon n’envoie aucune invitation.", { glossary: ["participant", "responsabilite", "invitation-privee"] }),
    step("new-governed-documents", "governed-journey-documents-section", "Documents attendus", "Indiquez uniquement les documents nécessaires. Ils deviennent des attentes de suivi ; aucun fichier n’est demandé ou reçu automatiquement.", { glossary: ["document-attendu"] }),
    step("new-governed-confidentiality", "governed-journey-confidentiality", "Règles de confidentialité", "Relisez les règles qui limiteront le cadre préparé. Aucun accès n’est ouvert lors de cette saisie.", { glossary: ["perimetre-d-acces", "acces-gouverne"] }),
    step("new-governed-actions", "governed-journey-first-actions", "Premières actions", "Ces lignes préparent les premières interventions humaines. Elles ne constituent pas un workflow automatique.", { glossary: ["etape-de-parcours", "responsabilite"] }),
  ] },
  { id: "create-manually", title: "Créer sans assistance", description: "Utiliser les contrôles manuels réellement disponibles.", steps: [
    step("new-governed-manual", "manual-governed-journey-form", "Mode manuel", "Ce formulaire crée directement un brouillon après votre envoi volontaire. Il ne génère aucune proposition IA.", { glossary: ["parcours-gouverne", "validation-humaine"] }),
    step("new-governed-manual-title", "manual-governed-journey-title", "Nom du parcours", "Saisissez un nom court et explicite. La Boussole ne préremplit aucune valeur.", { glossary: ["parcours-gouverne"] }),
    step("new-governed-manual-need", "governed-journey-need", "Besoin initial", "Décrivez la situation à traiter avec les informations nécessaires, sans donnée sensible inutile.", { glossary: ["objectif", "contexte"] }),
    step("new-governed-manual-workspace", "manual-governed-journey-workspace", "Workspace", "Choisissez un Workspace existant ou saisissez un nouveau nom. Si un nouveau nom est utilisé, le Workspace est créé avec le parcours lors de votre envoi explicite.", { glossary: ["workspace", "rattachement-manuel"] }),
    step("new-governed-manual-participants", "manual-governed-journey-participants", "Participants attendus", "Saisissez uniquement les participants nécessaires, une ligne par participant. Aucune invitation n’est envoyée.", { glossary: ["participant", "invitation-privee"] }),
    step("new-governed-manual-documents", "manual-governed-journey-documents", "Documents attendus", "Listez uniquement les documents nécessaires. Chaque ligne prépare un champ de suivi après la création.", { glossary: ["document-attendu"] }),
    step("new-governed-manual-create", "submit-governed-journey", "Créer le parcours", "Cette action crée le brouillon et son Workspace si nécessaire, puis ouvre le cockpit. Elle n’invite personne, n’ouvre aucun accès et ne lance aucun workflow.", { glossary: ["parcours-gouverne", "validation-humaine", "cockpit-consolide"] }),
  ] },
  { id: "validate-and-create", title: "Vérifier et créer", description: "Valider explicitement la proposition assistée.", steps: [
    step("new-governed-final-check", "governed-journey-proposal", "Dernière vérification", "Relisez le nom, l’objectif, les participants, les documents, la confidentialité et les premières actions avant toute création.", { glossary: ["validation-humaine", "proposition"] }),
    step("new-governed-validate", "validate-governed-journey", "Valider et créer", "Ce bouton est disponible lorsque la proposition et les champs obligatoires sont présents. Votre clic crée le brouillon puis ouvre son cockpit, sans invitation, accès ou workflow automatique.", { glossary: ["validation-humaine", "parcours-gouverne", "cockpit-consolide"] }),
  ] },
  { id: "discover-before-creating", title: "Découvrir un parcours avant de le créer", description: "Visiter une anatomie pédagogique locale, sans créer de donnée.", steps: [
    step("educational-preview-open", "governed-journey-educational-preview", "Voir l’exemple pédagogique", "Ouvrez une représentation statique du cockpit pour comprendre son organisation. Aucun parcours, Workspace ou objet métier n’est créé.", { glossary: ["parcours-gouverne", "cockpit-consolide"] }),
    step("educational-framework", "educational-journey-framework", "Cadre et Workspace", "Cette zone représente le besoin initial, le Workspace, la vue consolidée et des compteurs indicatifs. Plus tard, vous y lirez le contexte réel ; rien n’est rattaché automatiquement.", { glossary: ["objectif", "workspace", "contexte-de-travail"] }),
    step("educational-participants", "educational-journey-participants", "Participants et responsabilités", "Cette zone présente des rôles génériques, une invitation préparée et un accès gouverné. Dans un vrai parcours, vous les vérifierez humainement ; personne n’est invité automatiquement.", { glossary: ["participant", "responsabilite", "invitation-privee", "acces-gouverne"] }),
    step("educational-documents", "educational-journey-documents", "Documents et premières actions", "Cette zone distingue les documents attendus, la réception déclarative, la confidentialité et les actions humaines. Aucun fichier n’est reçu et aucune action ne démarre automatiquement.", { glossary: ["document-attendu", "perimetre-d-acces", "validation-humaine"] }),
    step("educational-communications", "educational-journey-communications", "Communications gouvernées", "Cette zone illustre les états préparée, active, terminée ou expirée. Plus tard, vous examinerez les communications réelles ; aucun média n’est lancé automatiquement.", { glossary: ["communication-securisee", "validation-humaine"] }),
    step("educational-interventions", "educational-journey-human-interventions", "Interventions humaines", "Cette zone rassemble les situations qui demanderont votre attention : invitation, document, dossier ou communication. Aucun traitement n’est exécuté par Goodissima à votre place.", { glossary: ["signal", "validation-humaine"] }),
    step("educational-review", "educational-journey-review", "Revue de gouvernance", "Cette zone présente le motif, la question à trancher, l’assistant facultatif et la conduite humaine. Une revue réelle doit être examinée et conduite par une personne ; la V1 ne décide jamais automatiquement.", { glossary: ["revue", "conduite-humaine", "validation-humaine"] }),
    step("educational-preview-close", "close-governed-journey-educational-preview", "Fermer la visite", "Fermez cette représentation pour revenir à la création. Rien n’a été enregistré et aucune action métier n’a été déclenchée.", { glossary: ["parcours-gouverne"] }),
  ] },
];
export const newGovernedJourneySteps = newGovernedJourneySequences.flatMap((sequence) => sequence.steps);
