import { compareMemoryPeriods, explainDecision, getMemoryObjectTrace, getMemoryStateAt, getMemoryTimeline, reconstructAccessAt } from "@/lib/governed-memory/read/service";
import { authenticateGovernedMemoryRequester } from "./auth";
import { parseAccessQuery, parseCompareQuery, parseExplanationQuery, parseId, parseObjectType, parseStateQuery, parseTimelineQuery, parseTraceQuery } from "./query-parsers";
import { governedMemoryHttpResponse } from "./response-mapper";

type CaseParams = { relationCaseId: string };
const query = (request: Request) => new URL(request.url).searchParams;

export function handleMemoryState(request: Request, params: CaseParams) { return governedMemoryHttpResponse(async () => { const { requesterUserId } = await authenticateGovernedMemoryRequester(); const relationCaseId = parseId(params.relationCaseId, "relationCaseId"); return getMemoryStateAt({ relationCaseId, requesterUserId, ...parseStateQuery(query(request)) }); }); }
export function handleMemoryComparison(request: Request, params: CaseParams) { return governedMemoryHttpResponse(async () => { const { requesterUserId } = await authenticateGovernedMemoryRequester(); const relationCaseId = parseId(params.relationCaseId, "relationCaseId"); return compareMemoryPeriods({ relationCaseId, requesterUserId, ...parseCompareQuery(query(request)) }); }); }
export function handleDecisionExplanation(request: Request, params: CaseParams & { decisionId: string }) { return governedMemoryHttpResponse(async () => { const { requesterUserId } = await authenticateGovernedMemoryRequester(); const relationCaseId = parseId(params.relationCaseId, "relationCaseId"); const decisionId = parseId(params.decisionId, "decisionId"); return explainDecision({ relationCaseId, requesterUserId, decisionId, ...parseExplanationQuery(query(request)) }); }); }
export function handleAccessReconstruction(request: Request, params: CaseParams) { return governedMemoryHttpResponse(async () => { const { requesterUserId } = await authenticateGovernedMemoryRequester(); const relationCaseId = parseId(params.relationCaseId, "relationCaseId"); const parsed = parseAccessQuery(query(request)); return reconstructAccessAt({ relationCaseId, requesterUserId, ...parsed, subjectUserId: parsed.subjectUserId ?? (parsed.subjectRepresentationId ? undefined : requesterUserId) }); }); }
export function handleMemoryTimeline(request: Request, params: CaseParams) { return governedMemoryHttpResponse(async () => { const { requesterUserId } = await authenticateGovernedMemoryRequester(); const relationCaseId = parseId(params.relationCaseId, "relationCaseId"); return getMemoryTimeline({ relationCaseId, requesterUserId, ...parseTimelineQuery(query(request)) }); }); }
export function handleMemoryObjectTrace(request: Request, params: CaseParams & { objectType: string; objectId: string }) { return governedMemoryHttpResponse(async () => { const { requesterUserId } = await authenticateGovernedMemoryRequester(); const relationCaseId = parseId(params.relationCaseId, "relationCaseId"); const objectType = parseObjectType(params.objectType); const objectId = parseId(params.objectId, "objectId"); return getMemoryObjectTrace({ relationCaseId, requesterUserId, objectType, objectId, ...parseTraceQuery(query(request)) }); }); }
