import Link from "next/link";
import { unstable_noStore as noStore } from "next/cache";
import { PlatformNavigation } from "@/components/PlatformNavigation";
import { getCurrentPrismaUser } from "@/lib/auth";
import { getGovernancePilotage, type GovernancePilotageSignal, type PilotageSignalKind } from "@/lib/governance-pilotage-repository";

export const dynamic = "force-dynamic";
function date(value: Date | null) { return value ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(value) : null; }
function Cards({ signals }: { signals: GovernancePilotageSignal[] }) { return signals.length ? <div className="grid gap-3 lg:grid-cols-2">{signals.map((signal) => <article key={signal.id} className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-[#247f88]">{signal.title}</p><h3 className="mt-1 font-bold text-slate-950">{signal.subject}</h3></div>{signal.date ? <span className="text-xs text-slate-500">{date(signal.date)}</span> : null}</div><p className="mt-2 text-sm text-slate-700">Parcours : {signal.journey}</p><p className="text-xs text-slate-500">{signal.workspace}{signal.portfolio ? ` · ${signal.portfolio}` : ""}</p><p className="mt-3 text-sm text-slate-600">{signal.reason}</p><Link href={signal.href} className="mt-3 inline-block rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">{signal.actionLabel}</Link></article>)}</div> : <p className="rounded-xl border bg-white p-4 text-sm text-slate-500">Aucun signal dans cette section.</p>; }
const sections: Array<{ kind: PilotageSignalKind; title: string }> = [{ kind: "ACTION", title: "À traiter maintenant" }, { kind: "UPCOMING", title: "Réunions à venir" }, { kind: "ACCESS", title: "Accès invités" }, { kind: "RECENT", title: "Communications récentes" }, { kind: "HISTORY", title: "Réunions terminées ou annulées" }];
export default async function GovernancePilotagePage() { noStore(); const owner = await getCurrentPrismaUser(); const data = await getGovernancePilotage(owner.id); return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><PlatformNavigation active="governance" organizationName={owner.name || "Organisation Goodissima"} /><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-[#247f88]">Signaux déterministes · données réelles</p><h1 className="mt-1 text-3xl font-bold">Salle de pilotage</h1><p className="mt-2 text-sm text-slate-600">Cette page indique où une intervention humaine est nécessaire. Elle ne déclenche aucun envoi, accès, média ou workflow.</p></div><Link href="/gouvernance" className="text-sm font-bold underline">Retour à la gouvernance</Link></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">À traiter</p><p className="text-2xl font-bold">{data.signals.filter((s) => s.kind === "ACTION").length}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">Parcours actifs</p><p className="text-2xl font-bold">{data.activeJourneyCount}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">Workspaces</p><p className="text-2xl font-bold">{data.workspaces.length}</p></div></div>{sections.map((section) => <section key={section.kind} className="mt-8"><h2 className="mb-3 text-xl font-bold">{section.title}</h2><Cards signals={data.signals.filter((signal) => signal.kind === section.kind)} /></section>)}<section className="mt-8"><h2 className="mb-3 text-xl font-bold">Workspaces / Portfolios</h2><div className="grid gap-3 lg:grid-cols-2">{data.workspaces.map((workspace) => <article key={workspace.id} className="rounded-xl border bg-white p-4"><h3 className="font-bold">{workspace.name}</h3><p className="text-sm text-slate-600">{workspace.portfolio ? `Portfolio : ${workspace.portfolio}` : "Sans portfolio"}</p><p className="mt-2 text-xs text-slate-500">{workspace.journeyCount} parcours · {workspace.caseCount} dossiers · {workspace.linkCount} liens · statut {workspace.status}</p></article>)}</div></section></main>; }
