import assert from "node:assert/strict"; import { readFileSync } from "node:fs"; import test from "node:test";
const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
test("Global exposes an explicit real form according to policy", () => { const global = read("components/directory/GlobalDirectory.tsx"); const form = read("components/directory/ContactRequestForm.tsx"); for (const text of ["Demander un contact", "Demander un échange par message", "Fermé aux nouvelles demandes", "Votre représentation", "Motif", "Canaux demandés", "Confirmer et envoyer"]) assert.ok(`${global}\n${form}`.includes(text)); assert.match(form, /if \(submitting \|\| sent\) return/); assert.match(form, /router\.refresh\(\)/); });
test("Moi exposes incoming, outgoing and human decisions", () => { const panel = read("components/directory/ContactRequestsPanel.tsx"); for (const text of ["Reçues", "Envoyées", "Accepter", "Refuser", "Reporter", "Reprendre", "Annuler", "ceci n’est pas encore un contact"]) assert.ok(panel.includes(text)); assert.match(panel, /expectedUpdatedAt/); assert.match(panel, /window\.confirm/); });
test("contacts remain honestly unavailable", () => { const overview = read("components/directory/MyDirectoryOverview.tsx"); assert.ok(overview.includes("Les contacts seront créés dans un prochain lot à partir des demandes acceptées.")); });
test("sender receives accessible persistent success and a direct outgoing link", () => { const form = read("components/directory/ContactRequestForm.tsx"); for (const text of ["Votre demande de contact a bien été envoyée.", "Vous pouvez suivre son état dans Moi > Demandes > Envoyées.", "Voir mes demandes envoyées"]) assert.ok(form.includes(text)); assert.match(form, /formRef\.current\?\.reset\(\)/); assert.match(form, /setOpen\(false\)/); assert.match(form, /setSent\(true\)/); assert.match(form, /if \(submitting \|\| sent\) return/); assert.match(form, /aria-live/); assert.match(form, /feedbackRef\.current\?\.focus/); assert.match(form, /\/annuaire\?tab=moi&requests=outgoing/); });
test("sender errors are distinct and never report false success", () => { const form = read("components/directory/ContactRequestForm.tsx"); for (const code of ["CONFLICT", "SELF_REPRESENTATION", "SAME_OWNER", "POLICY_CLOSED", "POLICY_MESSAGE_ONLY", "NOT_FOUND"]) assert.ok(form.includes(code)); assert.match(form, /if \(!response\.ok\)/); assert.match(form, /isConfirmedContactRequestCreation\(response\.status, payload\)/); assert.ok(form.includes("La demande n’a pas été enregistrée.")); assert.match(form, /erreur technique/); });
test("receiver sees pending count, priority callout and complete cards", () => { const panel = read("components/directory/ContactRequestsPanel.tsx"); for (const text of ["demandes reçues nécessitent votre attention", "demandes de contact en attente", "Voir les demandes reçues", "Représentation source", "Représentation cible", "Motif", "Canaux demandés", "Statut", "Date d’envoi", "Date limite", "Cette demande nécessite votre décision."]) assert.ok(panel.includes(text)); assert.match(panel, /pendingCount/); assert.match(panel, /initialPending \? "incoming" : initialTab/); });
test("real mutation responses update the active list and preserve its tab", () => { const panel = read("components/directory/ContactRequestsPanel.tsx"); assert.match(panel, /payload\.request/); assert.match(panel, /setIncoming\(update\)/); assert.match(panel, /setOutgoing\(update\)/); assert.match(panel, /router\.refresh\(\)/); assert.match(panel, /La liste et le compteur ont été mis à jour/); assert.doesNotMatch(panel, /setTab\("incoming"\).*router\.refresh/s); });
