import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");

test("POST returns 201 only after a complete persisted confirmation", () => { const route = read("app/api/directory/contact-requests/route.ts"); assert.match(route, /await createContactRequest/); assert.match(route, /persisted\?\.id/); assert.match(route, /persisted\.status !== "PENDING"/); assert.match(route, /persisted\.requesterRepresentation\?\.id/); assert.match(route, /persisted\.targetRepresentation\?\.id/); assert.match(route, /persisted\.requestedChannels/); assert.match(route, /status: 201/); assert.ok(route.indexOf("status: 201") > route.indexOf("CONTACT_REQUEST_RESPONSE_INCOMPLETE")); });
test("transaction creates request, channels and CREATED then rereads the row", () => { const repository = read("lib/directory/contact-request-repository.ts"); assert.match(repository, /database\.\$transaction\(async \(tx\)/); assert.match(repository, /tx\.contactRequest\.create/); assert.match(repository, /requestedChannels: \{ create:/); assert.match(repository, /events: \{ create: \{ type: "CREATED"/); assert.match(repository, /tx\.contactRequest\.findUnique/); assert.match(repository, /persisted\.requestedChannels\.length/); assert.match(repository, /persisted\.events\.length !== 1/); assert.match(repository, /throw new Error\("CONTACT_REQUEST_PERSISTENCE_CONFIRMATION_FAILED"\)/); });
test("Prisma exceptions and rollback cannot become an API success", () => { const route = read("app/api/directory/contact-requests/route.ts"); const repository = read("lib/directory/contact-request-repository.ts"); assert.doesNotMatch(repository, /catch\s*\([^)]*\)[\s\S]*outcome:\s*"CREATED"/); assert.match(route, /catch \(error\)[\s\S]*directoryApiError\(error\)/); assert.match(route, /\[directory\.contact-request\.create\] failed/); });
test("Preview diagnostic logs only safe database coordinates and request id", () => { const route = read("app/api/directory/contact-requests/route.ts"); assert.match(route, /hostname/); assert.match(route, /pathname/); assert.match(route, /searchParams\.get\("schema"\)/); assert.match(route, /requestId: persisted\.id/); assert.doesNotMatch(route, /console\.(?:info|error)\([^\n]*DATABASE_URL/); assert.doesNotMatch(route, /password/); });
