import type { OpportunityCriteriaV1 } from "../contracts.ts";
import type { OpportunityComparison } from "./types.ts";

export function normalizeMatchText(value: string) { return value.trim().toLocaleLowerCase("fr").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[’']/g, " ").replace(/[^a-z0-9]+/g, " ").trim(); }
const unknown = (criterion: OpportunityComparison["criterion"], label: string): OpportunityComparison => ({ criterion, outcome: "UNKNOWN", label });
const minutes = (value: string) => { const [hours, mins] = value.split(":").map(Number); return hours * 60 + mins; };
const overlap = (aFrom: string, aTo: string, bFrom: string, bTo: string) => Math.max(minutes(aFrom), minutes(bFrom)) < Math.min(minutes(aTo), minutes(bTo));

export function compareCategory(a?: string, b?: string): OpportunityComparison { if (!a || !b) return unknown("category", "Catégorie non renseignée"); return normalizeMatchText(a) === normalizeMatchText(b) ? { criterion: "category", outcome: "COMPATIBLE", label: `Catégorie compatible : ${a}` } : unknown("category", "Catégories différentes à examiner"); }
export function compareLocation(a?: string[], b?: string[]): OpportunityComparison { if (!a?.length || !b?.length) return unknown("location", "Localisation non renseignée"); const right = new Set(b.map(normalizeMatchText)); const common = a.find((value) => right.has(normalizeMatchText(value))); return common ? { criterion: "location", outcome: "COMPATIBLE", label: common } : unknown("location", "Localisations différentes à examiner"); }
export function compareDays(a?: OpportunityCriteriaV1["availability"], b?: OpportunityCriteriaV1["availability"]): OpportunityComparison { if (!a?.days?.length || !b?.days?.length) return unknown("days", "Jours non renseignés"); const common = a.days.filter((day) => b.days?.includes(day)); return { criterion: "days", outcome: common.length ? "COMPATIBLE" : "INCOMPATIBLE", label: common.length ? `Jours communs : ${common.join(", ")}` : "Aucun jour commun" }; }
export function compareTime(a?: OpportunityCriteriaV1["availability"], b?: OpportunityCriteriaV1["availability"]): OpportunityComparison { if (!a?.timeFrom || !a.timeTo || !b?.timeFrom || !b.timeTo) return unknown("time", "Horaires incomplets"); if (a.timezone && b.timezone && a.timezone !== b.timezone) return unknown("time", "Fuseaux horaires différents"); return { criterion: "time", outcome: overlap(a.timeFrom, a.timeTo, b.timeFrom, b.timeTo) ? "COMPATIBLE" : "INCOMPATIBLE", label: overlap(a.timeFrom, a.timeTo, b.timeFrom, b.timeTo) ? `${a.timeFrom.replace(":", "h")}–${a.timeTo.replace(":", "h")} compatible` : "Horaires sans chevauchement" }; }
export function compareDate(a?: OpportunityCriteriaV1["dateWindow"], b?: OpportunityCriteriaV1["dateWindow"]): OpportunityComparison { if (!a || !b) return unknown("date", "Dates non renseignées"); if (a.from && a.to && b.from && b.to) return { criterion: "date", outcome: a.from <= b.to && b.from <= a.to ? "COMPATIBLE" : "INCOMPATIBLE", label: a.from <= b.to && b.from <= a.to ? "Fenêtres de dates compatibles" : "Fenêtres de dates disjointes" }; if (a.from && b.to && a.from > b.to || b.from && a.to && b.from > a.to) return { criterion: "date", outcome: "INCOMPATIBLE", label: "Fenêtres de dates disjointes" }; return unknown("date", "Fenêtres de dates partielles"); }
export function comparePrice(a?: OpportunityCriteriaV1["priceRange"], b?: OpportunityCriteriaV1["priceRange"]): OpportunityComparison { if (!a || !b) return unknown("price", "Rémunération non renseignée"); if (a.currency !== b.currency) return unknown("price", "Devises différentes"); if (!a.unit || !b.unit || normalizeMatchText(a.unit) !== normalizeMatchText(b.unit)) return unknown("price", "Unité de prix non comparable"); if (a.min === undefined || a.max === undefined || b.min === undefined || b.max === undefined) return unknown("price", "Plage de prix incomplète"); const compatible = Math.max(a.min, b.min) <= Math.min(a.max, b.max); return { criterion: "price", outcome: compatible ? "COMPATIBLE" : "INCOMPATIBLE", label: compatible ? "Plages de prix compatibles" : "Plages de prix disjointes" }; }
