import type { GovernedMemoryDecisionStatus, GovernedMemoryDisputeStatus, GovernedMemoryEvidenceLevel, GovernedMemoryFactStatus, GovernedMemoryPermission, GovernedMemoryRole, GovernedMemorySourceKind, GovernedMemorySourceStatus, GovernedMemoryTargetType, GovernedMemoryValidationDecision } from "@prisma/client";

export type GovernedMemoryKnowledgeMode = "KNOWN_AT_DATE" | "CURRENT_KNOWLEDGE_ABOUT_DATE" | "KNOWN_AT_EACH_DATE" | "CURRENT_KNOWLEDGE_ABOUT_PERIOD";
export type GovernedMemoryReadInclude = "FACTS" | "DECISIONS" | "SOURCES" | "DISPUTES" | "VALIDATIONS" | "TIMELINE" | "ACCESS";
export type GovernedMemoryKnowledgeTiming = "KNOWN_THEN" | "RECORDED_LATER";
export type GovernedMemoryRedactionLevel = "EXISTENCE_DISCLOSED" | "FULLY_HIDDEN";

export type GetMemoryStateAtInput = { relationCaseId: string; requesterUserId: string; referenceDate: string; knowledgeMode: "KNOWN_AT_DATE" | "CURRENT_KNOWLEDGE_ABOUT_DATE"; include?: GovernedMemoryReadInclude[]; limit?: number; cursor?: string };
export type CompareMemoryPeriodsInput = { relationCaseId: string; requesterUserId: string; from: string; to: string; knowledgeMode: "KNOWN_AT_EACH_DATE" | "CURRENT_KNOWLEDGE_ABOUT_PERIOD"; include?: GovernedMemoryReadInclude[] };
export type ExplainDecisionInput = { relationCaseId: string; requesterUserId: string; decisionId: string; referenceDate?: string };
export type ReconstructAccessAtInput = { relationCaseId: string; requesterUserId: string; subjectUserId?: string; subjectRepresentationId?: string; referenceDate: string };

export type GovernedMemoryVisibleReference = { type: GovernedMemoryTargetType; id: string };
export type GovernedMemorySupersessionView = { relationType: "REPLACES" | "CORRECTS" | "CANCELS" | "COMPLEMENTS"; relatedId: string; recordedAt: string };
export type GovernedMemoryFactView = { id: string; statement: string; statusAtReference: GovernedMemoryFactStatus; evidenceLevel: GovernedMemoryEvidenceLevel; effectiveFrom: string; effectiveUntil: string | null; recordedAt: string; knowledgeTiming: GovernedMemoryKnowledgeTiming; sourceRefs: GovernedMemoryVisibleReference[]; disputeState: "NONE" | GovernedMemoryDisputeStatus; supersession?: GovernedMemorySupersessionView };
export type GovernedMemoryDecisionView = { id: string; title: string; declaredRationale: string; statusAtReference: GovernedMemoryDecisionStatus; decidedByUserId: string; validatedByUserId: string | null; decidedAt: string; validatedAt: string | null; effectiveFrom: string; effectiveUntil: string | null; recordedAt: string; knowledgeTiming: GovernedMemoryKnowledgeTiming; sourceRefs: GovernedMemoryVisibleReference[]; factRefs: GovernedMemoryVisibleReference[]; disputeState: "NONE" | GovernedMemoryDisputeStatus; supersession?: GovernedMemorySupersessionView; reservations: string | null; consequences: string | null };
export type GovernedMemorySourceView = { id: string; kind: GovernedMemorySourceKind; statusAtReference: GovernedMemorySourceStatus; title: string; authoredAt: string | null; receivedAt: string | null; recordedAt: string; knowledgeTiming: GovernedMemoryKnowledgeTiming; available: boolean; restricted: boolean };
export type GovernedMemoryDisputeView = { id: string; targetType: GovernedMemoryTargetType; targetId: string; statusAtReference: GovernedMemoryDisputeStatus; raisedAt: string; resolvedAt: string | null; reason: string; resolution: string | null };
export type GovernedMemoryValidationView = { id: string; targetType: GovernedMemoryTargetType; targetId: string; validatorUserId: string; validatorRole: GovernedMemoryRole; decision: GovernedMemoryValidationDecision; rationale: string | null; reservations: string | null; validatedAt: string };
export type GovernedMemoryTimelineItem = { id: string; type: string; actorType: "HUMAN" | "SYSTEM"; actorUserId: string | null; objectType: GovernedMemoryTargetType; objectId: string; occurredAt: string; recordedAt: string; summary: string };
export type GovernedMemoryAccessView = { id: string; subjectType: "USER" | "REPRESENTATION"; subjectId: string; permission: GovernedMemoryPermission; resourceType: GovernedMemoryTargetType | null; resourceId: string | null; effectiveFrom: string; effectiveUntil: string | null; revokedAt: string | null; stateAtReference: "ACTIVE" | "REVOKED" | "EXPIRED" | "NOT_YET_EFFECTIVE" | "RESIDUAL" };
export type GovernedMemoryRoleView = { id: string; userId: string; role: GovernedMemoryRole; assignedAt: string; revokedAt: string | null; activeAtReference: boolean };

export type GovernedMemoryReadLimitationCode = "SOURCE_NOT_LINKED" | "SOURCE_REDACTED" | "SOURCE_UNAVAILABLE" | "RETROACTIVE_INFORMATION" | "STATUS_HISTORY_INCOMPLETE" | "CAUSALITY_NOT_ESTABLISHED" | "ACCESS_NOT_EQUAL_TO_CONSULTATION" | "CONSULTATION_LOG_UNAVAILABLE" | "OPEN_DISPUTE" | "INCOMPLETE_TEMPORAL_COVERAGE" | "POLYMORPHIC_REFERENCE_UNVERIFIED" | "CURRENT_ACCESS_RESTRICTED" | "PAGE_LIMIT_REACHED";
export type GovernedMemoryReadLimitation = { code: GovernedMemoryReadLimitationCode; scope: "RESULT" | "FACT" | "DECISION" | "SOURCE" | "ACCESS"; objectId: string | null; message: string; severity: "INFO" | "WARNING" | "MATERIAL" };
export type GovernedMemoryRedaction = { level: GovernedMemoryRedactionLevel; objectType: GovernedMemoryTargetType; disclosedId: string | null; reasonCode: "CURRENT_ACCESS_RESTRICTED" | "SOURCE_RESTRICTED" | "SOURCE_UNAVAILABLE" };
export type GovernedMemoryPagination = { limit: number; nextCursor: string | null; hasMore: boolean };
export type GovernedMemoryChange = { id: string; type: string; changedAt: string; before: unknown; after: unknown; evidenceRefs: GovernedMemoryVisibleReference[]; certainty: "EXACT" | "RECONSTRUCTED" | "INCOMPLETE" };
export type GovernedMemoryChangeSet = { factsAdded: GovernedMemoryChange[]; factsRemovedFromEffectiveState: GovernedMemoryChange[]; factsChanged: GovernedMemoryChange[]; decisionsAdded: GovernedMemoryChange[]; decisionsSuperseded: GovernedMemoryChange[]; decisionsCancelled: GovernedMemoryChange[]; sourcesAdded: GovernedMemoryChange[]; sourcesRestricted: GovernedMemoryChange[]; disputesOpened: GovernedMemoryChange[]; disputesResolved: GovernedMemoryChange[]; permissionsGranted: GovernedMemoryChange[]; permissionsRevoked: GovernedMemoryChange[]; roleAssignmentsChanged: GovernedMemoryChange[] };

export type GovernedMemoryReadResult = { relationCaseId: string; referenceDate?: string; period?: { from: string; to: string }; knowledgeMode: GovernedMemoryKnowledgeMode; generatedAt: string; facts: GovernedMemoryFactView[]; decisions: GovernedMemoryDecisionView[]; sources: GovernedMemorySourceView[]; disputes: GovernedMemoryDisputeView[]; validations: GovernedMemoryValidationView[]; timeline: GovernedMemoryTimelineItem[]; access: GovernedMemoryAccessView[]; roles: GovernedMemoryRoleView[]; changes?: GovernedMemoryChangeSet; limitations: GovernedMemoryReadLimitation[]; redactions: GovernedMemoryRedaction[]; pagination?: GovernedMemoryPagination };

export type GovernedMemoryDecisionExplanation = { decision: GovernedMemoryDecisionView; declaredRationale: string; explicitSupportingFacts: GovernedMemoryFactView[]; explicitSupportingSources: GovernedMemorySourceView[]; relatedPriorDecisions: GovernedMemoryDecisionView[]; laterConsequences: string | null; openDisputes: GovernedMemoryDisputeView[]; validations: GovernedMemoryValidationView[]; events: GovernedMemoryTimelineItem[]; limitations: GovernedMemoryReadLimitation[]; redactions: GovernedMemoryRedaction[] };
export type GovernedMemoryAccessReconstruction = { subject: { type: "USER" | "REPRESENTATION"; id: string }; referenceDate: string; activeRoles: GovernedMemoryRoleView[]; activeGrants: GovernedMemoryAccessView[]; residualGrants: GovernedMemoryAccessView[]; revokedGrants: GovernedMemoryAccessView[]; effectivePermissions: GovernedMemoryPermission[]; restrictedResources: { type: GovernedMemoryTargetType; id: string | null }[]; limitations: GovernedMemoryReadLimitation[]; redactions: GovernedMemoryRedaction[] };

export type ReadCursor = { recordedAt: string; id: string };
