import Link from "next/link";
import { PlatformNavigation } from "@/components/PlatformNavigation";
import { getCurrentPrismaUser } from "@/lib/auth";
import { getGovernancePortfolioSummaries } from "@/lib/governance-portfolio-repository";
import { getGovernancePilotage } from "@/lib/governance-pilotage-repository";
export const dynamic = "force-dynamic";
export default async function GovernancePortfoliosPage() {
  const owner = await getCurrentPrismaUser(); const portfolios = await getGovernancePortfolioSummaries(owner.id);
  const rows = await Promise.all(portfolios.map(async (portfolio) => ({ portfolio, pilotage: await getGovernancePilotage(owner.id, portfolio.id) })));
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><PlatformNavigation active="governance" organizationName={owner.name || "Organisation Goodissima"} /><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-[#247f88]">Gouvernance produit</p><h1 className="text-3xl font-bold">Portfolios</h1><p className="mt-2 text-sm text-slate-600">Regroupez plusieurs Workspaces sans déclencher d’accès, réunion, notification ou action.</p></div><Link href="/gouvernance/portfolios/nouveau" className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white">Créer un Portfolio</Link></div>{rows.length ? <div className="mt-6 grid gap-4 lg:grid-cols-2">{rows.map(({ portfolio, pilotage }) => { const meetings = pilotage.signals.filter((signal) => signal.id.startsWith("open-")).length; const latest = pilotage.signals.map((signal) => signal.date).filter((value): value is Date => Boolean(value)).sort((a,b) => b.getTime()-a.getTime())[0]; return <article key={portfolio.id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold uppercase text-[#247f88]">{portfolio.kindLabel} · {portfolio.statusLabel}</p><h2 className="mt-1 text-xl font-bold">{portfolio.name}</h2></div><span className="text-xs text-slate-500">{latest ? `Activité ${latest.toLocaleDateString("fr-FR")}` : "Aucune activité"}</span></div>{portfolio.description ? <p className="mt-2 text-sm text-slate-600">{portfolio.description}</p> : null}<div className="mt-4 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4"><p>{portfolio.workspaceCount} Workspaces</p><p>{portfolio.journeyCount} parcours</p><p>{meetings} réunions prêtes</p><p>{pilotage.signals.filter((s) => s.kind === "ACTION").length} signaux</p></div><div className="mt-4 flex gap-2"><Link href={`/gouvernance/portfolios/${portfolio.id}`} className="rounded-lg border px-3 py-2 text-xs font-bold">Ouvrir le Portfolio</Link><Link href={`/gouvernance/portfolios/${portfolio.id}/pilotage`} className="rounded-lg bg-[#247f88] px-3 py-2 text-xs font-bold text-white">Salle de pilotage</Link></div></article>; })}</div> : <p className="mt-6 rounded-xl border bg-white p-5 text-sm text-slate-600">Aucun Portfolio réel pour le moment.</p>}</main>;
}
