export const dynamic = "force-dynamic";

import Link from "next/link";
import { LogoutButton } from "@/components/LogoutButton";
import { PlatformNavigation } from "@/components/PlatformNavigation";
import { getCurrentPrismaUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { ProductLifecycle, ProductObjectDefinition } from "@/components/ProductObjectClarity";

export default async function RelationsPage() {
  const owner = await getCurrentPrismaUser();
  const organizationName = owner.name && owner.name !== owner.email ? owner.name : "Organisation Goodissima";
  const relations = await prisma.relationCase.findMany({ where: { ownerId: owner.id }, orderBy: { createdAt: "desc" }, include: { gLink: { select: { title: true, city: true } } } });
  const pending = relations.filter((relation) => ["NEW", "WAITING_CANDIDATE", "WAITING_OWNER", "REVIEWING"].includes(relation.status)).length;
  const accepted = relations.filter((relation) => ["VALIDATED", "CLOSED"].includes(relation.status)).length;
  return <main className="mx-auto max-w-6xl px-6 py-10"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#247f88]">Espaces gouvernés</p><h1 className="mt-2 text-3xl font-bold">Relations</h1><ProductObjectDefinition object="relation" /></div><LogoutButton /></div><div className="mt-8"><PlatformNavigation active="relations" organizationName={organizationName} /></div><ProductLifecycle current="relation" /><section className="mt-6 rounded-3xl border bg-white p-6"><h2 className="text-xl font-bold">Workspace relationnel</h2><p className="mt-1 max-w-3xl text-sm text-slate-500">Relations en attente, relations acceptées, conversation, documents, demandes relationnelles, gouvernance et assistance IA sont accessibles depuis chaque espace relationnel.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl bg-amber-50 p-4"><p className="text-sm text-amber-800">Relations en attente</p><p className="mt-2 text-2xl font-bold text-amber-950">{pending}</p></div><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-sm text-emerald-800">Relations acceptées</p><p className="mt-2 text-2xl font-bold text-emerald-950">{accepted}</p></div><div className="rounded-2xl bg-cyan-50 p-4"><p className="text-sm text-cyan-800">Conversation & documents</p><p className="mt-2 text-2xl font-bold text-cyan-950">{relations.length}</p></div><div className="rounded-2xl bg-violet-50 p-4"><p className="text-sm text-violet-800">Assistance IA gouvernée</p><p className="mt-2 text-2xl font-bold text-violet-950">Disponible</p></div></div></section><div className="mt-6">{relations.length ? <div className="space-y-3">{relations.map((relation) => <article key={relation.id} className="flex flex-col gap-3 rounded-2xl border bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{relation.gLink.title}</h2><p className="mt-1 text-sm text-slate-500">{relation.candidateName} · {relation.gLink.city ?? "Localisation non précisée"}</p><p className="mt-2 text-xs text-slate-500">Annonce d'origine : <Link href={`/links/${relation.gLinkId}`} className="font-semibold text-[#247f88] underline">Voir l'annonce</Link></p><p className="mt-2 text-xs font-medium text-[#247f88]">Statut relationnel : {relation.status}</p></div><Link href={`/cases/${relation.id}`} className="rounded-xl bg-slate-900 px-4 py-2 text-center text-sm font-semibold text-white">Ouvrir la relation</Link></article>)}</div> : <div className="rounded-3xl border border-dashed bg-white p-10 text-center"><h2 className="font-semibold">Aucune relation ouverte</h2><p className="mt-2 text-sm text-slate-500">Une relation apparaîtra ici après acceptation d'une demande de mise en relation.</p></div>}</div></main>;
}
