export type GlossaryCategory = "Navigation" | "Publication" | "Relation" | "Confiance" | "Gouvernance" | "Assistance";

export type GlossaryTerm = {
  id: string;
  label: string;
  definition: string;
  example?: string;
  category: GlossaryCategory;
  searchAliases: string[];
  relatedTermIds: string[];
  targets: Array<{ dataBoussoleId: string; routes: string[] }>;
};

export const boussoleGlossary: readonly GlossaryTerm[] = [
  { id: "dashboard", label: "Dashboard", definition: "Vue d’ensemble de l’activité réelle du compte.", example: "Consulter les liens et événements récents.", category: "Navigation", searchAliases: ["tableau de bord", "accueil"], relatedTermIds: ["chronologie", "opportunite"], targets: [{ dataBoussoleId: "dashboard-menu", routes: ["/dashboard"] }] },
  { id: "lien-simple", label: "Lien simple", definition: "Formulaire public sécurisé que son propriétaire peut configurer.", example: "Recueillir une réponse structurée à un besoin.", category: "Publication", searchAliases: ["formulaire simple", "création de lien"], relatedTermIds: ["lien-securise", "dossier"], targets: [{ dataBoussoleId: "create-simple-link", routes: ["/dashboard", "/links/simple"] }] },
  { id: "lien-securise", label: "Lien sécurisé", definition: "Adresse publique contrôlée qui donne accès à une annonce ou à un formulaire.", example: "Partager une annonce par URL ou QR code.", category: "Publication", searchAliases: ["url publique", "lien public"], relatedTermIds: ["annonce", "admission"], targets: [{ dataBoussoleId: "dashboard-link-public-url", routes: ["/dashboard"] }, { dataBoussoleId: "opportunity-card-public-link", routes: ["/opportunities"] }, { dataBoussoleId: "copy-public-link", routes: ["/links/:linkId"] }] },
  { id: "annonce", label: "Annonce", definition: "Présentation publique d’un besoin ou d’une offre.", example: "Une annonce publiée est visible depuis son lien sécurisé.", category: "Publication", searchAliases: ["publication", "annonce publique"], relatedTermIds: ["opportunite", "lien-securise"], targets: [{ dataBoussoleId: "dashboard-link-public-view", routes: ["/dashboard"] }, { dataBoussoleId: "view-public-opportunity", routes: ["/opportunities"] }] },
  { id: "opportunite", label: "Opportunité", definition: "Besoin ou possibilité que l’utilisateur peut structurer puis publier.", example: "Préparer une recherche de partenaire.", category: "Publication", searchAliases: ["besoin", "offre"], relatedTermIds: ["annonce", "matching-relationnel"], targets: [{ dataBoussoleId: "dashboard-create-actions", routes: ["/dashboard"] }, { dataBoussoleId: "create-opportunity", routes: ["/opportunities"] }] },
  { id: "dossier", label: "Dossier", definition: "Contexte de relation créé à partir d’une réponse réelle.", example: "Une réponse admise peut ouvrir un dossier.", category: "Relation", searchAliases: ["conversation", "case"], relatedTermIds: ["candidat", "admission"], targets: [{ dataBoussoleId: "dashboard-link-case-count", routes: ["/dashboard"] }, { dataBoussoleId: "opportunity-card-case-count", routes: ["/opportunities"] }, { dataBoussoleId: "case-conversation", routes: ["/cases/:caseId"] }] },
  { id: "candidat", label: "Candidat", definition: "Personne ayant réellement répondu à une annonce et dont un dossier existe.", example: "Le terme n’est pas utilisé avant la création d’un dossier candidat.", category: "Relation", searchAliases: ["répondant", "personne candidate"], relatedTermIds: ["dossier", "correspondance-potentielle"], targets: [{ dataBoussoleId: "candidate-access-controls", routes: ["/cases/:caseId"] }] },
  { id: "matching-relationnel", label: "Matching relationnel", definition: "Analyse assistée de compatibilités qui restent à examiner humainement.", example: "Comparer un besoin à des opportunités existantes.", category: "Relation", searchAliases: ["matching", "rapprochement", "compatibilité"], relatedTermIds: ["correspondance-potentielle", "salle-pilotage"], targets: [{ dataBoussoleId: "dashboard-link-matching-status", routes: ["/dashboard"] }, { dataBoussoleId: "opportunity-matching-status", routes: ["/opportunities"] }, { dataBoussoleId: "link-matching-status", routes: ["/links/:linkId"] }] },
  { id: "correspondance-potentielle", label: "Correspondance potentielle", definition: "Compatibilité suggérée qui exige un examen et une décision humains.", example: "Vérifier les critères avant de décider de la suite.", category: "Relation", searchAliases: ["match", "correspondance à examiner"], relatedTermIds: ["matching-relationnel", "dossier"], targets: [{ dataBoussoleId: "review-link-matches", routes: ["/links/:linkId"] }] },
  { id: "admission", label: "Admission", definition: "Règle qui détermine qui peut répondre et créer un dossier.", example: "Autoriser tout le monde ou seulement les identités vérifiées.", category: "Confiance", searchAliases: ["qui peut répondre", "droit de répondre", "accès", "ouverte à tous", "personnes vérifiées"], relatedTermIds: ["identite-goodissima-verifiee", "dossier"], targets: [{ dataBoussoleId: "dashboard-link-admission", routes: ["/dashboard"] }, { dataBoussoleId: "opportunity-admission", routes: ["/opportunities"] }, { dataBoussoleId: "explain-link-admission", routes: ["/links/:linkId"] }] },
  { id: "identite-goodissima-verifiee", label: "Identité Goodissima vérifiée", definition: "Identité assortie d’une preuve de confiance reconnue par Goodissima.", example: "Exiger cette vérification avant la création d’un dossier.", category: "Confiance", searchAliases: ["identité vérifiée", "vérification identité"], relatedTermIds: ["admission"], targets: [{ dataBoussoleId: "directory-identity", routes: ["/annuaire"] }] },
  { id: "chronologie", label: "Chronologie", definition: "Suite datée des événements réellement enregistrés.", example: "Rouvrir un lien récemment créé.", category: "Navigation", searchAliases: ["timeline", "activité récente", "historique"], relatedTermIds: ["dashboard"], targets: [{ dataBoussoleId: "dashboard-recent-activity", routes: ["/dashboard"] }] },
  { id: "salle-pilotage", label: "Salle de pilotage", definition: "Vue des situations qui demandent une intervention humaine.", example: "Examiner un signal de matching.", category: "Gouvernance", searchAliases: ["pilotage", "signaux"], relatedTermIds: ["matching-relationnel", "parcours-gouverne"], targets: [{ dataBoussoleId: "pilotage-overview", routes: ["/gouvernance/pilotage"] }] },
  { id: "parcours-gouverne", label: "Parcours gouverné", definition: "Cadre structuré permettant d’organiser plusieurs participants, étapes, documents, revues et décisions autour d’une situation.", example: "Organiser une relation dans un Workspace.", category: "Gouvernance", searchAliases: ["parcours de confiance", "journey"], relatedTermIds: ["workspace", "revue"], targets: [{ dataBoussoleId: "create-governed-journey", routes: ["/gouvernance"] }] },
  { id: "workspace", label: "Workspace", definition: "Espace qui organise les parcours, liens, dossiers et communications appartenant à un même contexte.", example: "Rassembler plusieurs dossiers d’un même projet.", category: "Gouvernance", searchAliases: ["espace de travail", "espace"], relatedTermIds: ["portfolio", "parcours-gouverne"], targets: [{ dataBoussoleId: "workspace-list", routes: ["/gouvernance"] }] },
  { id: "portfolio", label: "Portfolio", definition: "Regroupement de plusieurs Workspaces dans une vue produit, métier ou organisationnelle.", example: "Suivre plusieurs projets sans modifier leur contenu.", category: "Gouvernance", searchAliases: ["portefeuille", "regroupement"], relatedTermIds: ["workspace", "revue"], targets: [{ dataBoussoleId: "create-portfolio", routes: ["/gouvernance", "/gouvernance/portfolios"] }] },
  { id: "revue", label: "Revue", definition: "Point de contrôle préparé puis conduit par des humains.", example: "Relire une situation avant de valider la suite.", category: "Gouvernance", searchAliases: ["revue gouvernance", "contrôle"], relatedTermIds: ["parcours-gouverne", "portfolio"], targets: [{ dataBoussoleId: "governance-reviews", routes: ["/gouvernance/parcours/:id/pilotage"] }] },
  { id: "gouvernance", label: "Gouvernance", definition: "Organisation structurée des responsabilités, participants, validations, revues et décisions d’un parcours.", example: "Piloter un parcours impliquant plusieurs acteurs.", category: "Gouvernance", searchAliases: ["gouverner", "organisation du parcours"], relatedTermIds: ["parcours-gouverne", "pilotage-global", "validation-humaine"], targets: [{ dataBoussoleId: "governance-overview", routes: ["/gouvernance"] }] },
  { id: "rattachement", label: "Rattachement", definition: "Association explicite d’un objet existant à un Workspace sans modifier ses accès ni son contenu.", category: "Gouvernance", searchAliases: ["rattacher", "associer au workspace"], relatedTermIds: ["workspace", "validation-humaine"], targets: [{ dataBoussoleId: "workspace-object-counts", routes: ["/gouvernance"] }] },
  { id: "pilotage-global", label: "Pilotage global", definition: "Vue transversale des signaux et situations de gouvernance qui nécessitent une attention humaine.", category: "Gouvernance", searchAliases: ["pilotage transversal", "salle globale"], relatedTermIds: ["salle-pilotage", "signal", "gouvernance"], targets: [{ dataBoussoleId: "open-global-governance-pilotage", routes: ["/gouvernance"] }] },
  { id: "pilotage-de-parcours", label: "Pilotage de parcours", definition: "Cockpit limité à l’état, aux participants, revues et décisions d’un parcours gouverné déterminé.", category: "Gouvernance", searchAliases: ["cockpit du parcours", "pilotage parcours"], relatedTermIds: ["parcours-gouverne", "pilotage-global"], targets: [{ dataBoussoleId: "open-governed-journey", routes: ["/gouvernance"] }] },
  { id: "participant", label: "Participant", definition: "Personne associée à un parcours avec un rôle et un accès gouvernés.", category: "Gouvernance", searchAliases: ["acteur", "membre du parcours"], relatedTermIds: ["parcours-gouverne", "invitation-privee"], targets: [{ dataBoussoleId: "governed-participants", routes: ["/gouvernance/parcours/:id/pilotage"] }] },
  { id: "etape-de-parcours", label: "Étape de parcours", definition: "Moment distinct du parcours comportant un objectif ou un résultat attendu. Une étape ne s’exécute pas automatiquement.", category: "Gouvernance", searchAliases: ["étape", "phase du parcours"], relatedTermIds: ["parcours-gouverne", "validation-humaine"], targets: [] },
  { id: "conduite-humaine", label: "Conduite humaine", definition: "Réalisation effective d’une revue ou d’une décision par une personne autorisée.", category: "Confiance", searchAliases: ["conduire humainement", "action humaine"], relatedTermIds: ["revue", "validation-humaine"], targets: [{ dataBoussoleId: "conduct-governance-review", routes: ["/gouvernance/parcours/:id/pilotage"] }] },
  { id: "invitation-privee", label: "Invitation privée", definition: "Accès limité préparé pour une personne et un parcours déterminés, sans envoi automatique.", category: "Confiance", searchAliases: ["invitation gouvernée", "invité"], relatedTermIds: ["participant", "acces-gouverne"], targets: [{ dataBoussoleId: "create-governed-invitation", routes: ["/gouvernance/parcours/:id/pilotage"] }] },
  { id: "acces-gouverne", label: "Accès gouverné", definition: "Accès limité par un rôle, un périmètre et une décision humaine explicite.", category: "Confiance", searchAliases: ["accès privé", "accès invité"], relatedTermIds: ["invitation-privee", "validation-humaine"], targets: [{ dataBoussoleId: "create-governed-invitation", routes: ["/gouvernance/parcours/:id/pilotage"] }] },
  { id: "cockpit-consolide", label: "Cockpit consolidé", definition: "Vue qui rassemble les informations et objets rattachés à un Workspace ou à un parcours.", category: "Gouvernance", searchAliases: ["vue consolidée", "cockpit"], relatedTermIds: ["workspace", "pilotage-de-parcours"], targets: [{ dataBoussoleId: "open-governed-journey", routes: ["/gouvernance"] }] },
  { id: "contexte-de-travail", label: "Contexte de travail", definition: "Périmètre métier ou projet utilisé pour organiser des objets liés dans un Workspace.", category: "Gouvernance", searchAliases: ["contexte", "espace métier"], relatedTermIds: ["workspace", "rattachement"], targets: [{ dataBoussoleId: "workspace-category", routes: ["/gouvernance"] }] },
  { id: "signal", label: "Signal", definition: "Indication visible qu’une situation mérite une lecture ou une intervention humaine.", category: "Gouvernance", searchAliases: ["alerte", "attention requise"], relatedTermIds: ["pilotage-global", "validation-humaine"], targets: [{ dataBoussoleId: "pilotage-signals", routes: ["/gouvernance/pilotage"] }] },
  { id: "annuaire-goodissima", label: "Annuaire Goodissima", definition: "Espace transversal consacré aux identités, à la confiance et à la préparation humaine des contacts.", category: "Confiance", searchAliases: ["annuaire", "répertoire Goodissima"], relatedTermIds: ["identite", "confiance", "contact"], targets: [{ dataBoussoleId: "open-goodissima-directory", routes: ["/gouvernance"] }] },
  { id: "identite", label: "Identité", definition: "Informations permettant de distinguer une personne ou une organisation dans un cadre de confiance.", category: "Confiance", searchAliases: ["identité Goodissima", "personne connue"], relatedTermIds: ["confiance", "annuaire-goodissima"], targets: [{ dataBoussoleId: "directory-identity", routes: ["/annuaire"] }] },
  { id: "confiance", label: "Confiance", definition: "Ensemble des informations et validations utilisées pour préparer une relation de façon maîtrisée.", category: "Confiance", searchAliases: ["trust", "niveau de confiance"], relatedTermIds: ["identite", "validation-humaine"], targets: [{ dataBoussoleId: "directory-identity", routes: ["/annuaire"] }] },
  { id: "contact", label: "Contact", definition: "Personne ou organisation qu’un utilisateur peut décider de consulter ou de contacter volontairement.", category: "Relation", searchAliases: ["correspondant", "personne"], relatedTermIds: ["annuaire-goodissima", "validation-humaine"], targets: [{ dataBoussoleId: "open-goodissima-directory", routes: ["/gouvernance"] }] },
  { id: "rattachement-manuel", label: "Rattachement manuel", definition: "Action volontaire qui organise un parcours, un lien ou un dossier existant dans un Workspace sans recréer cet objet.", category: "Gouvernance", searchAliases: ["rattacher manuellement", "organiser dans un workspace"], relatedTermIds: ["rattachement", "workspace", "validation-humaine"], targets: [{ dataBoussoleId: "governed-journeys-without-workspace", routes: ["/gouvernance"] }] },
  { id: "parcours-sans-workspace", label: "Parcours sans Workspace", definition: "Parcours gouverné existant qui n’est actuellement rattaché à aucun Workspace.", category: "Gouvernance", searchAliases: ["parcours non rattaché", "parcours à organiser"], relatedTermIds: ["parcours-gouverne", "workspace", "rattachement-manuel"], targets: [{ dataBoussoleId: "first-unassigned-governed-journey", routes: ["/gouvernance"] }] },
  { id: "dossier-sans-workspace", label: "Dossier sans Workspace", definition: "Dossier relationnel existant qui n’est actuellement organisé dans aucun Workspace.", category: "Gouvernance", searchAliases: ["dossier non rattaché", "dossier à organiser"], relatedTermIds: ["dossier-relationnel", "workspace", "rattachement-manuel"], targets: [{ dataBoussoleId: "first-unassigned-relational-case", routes: ["/gouvernance"] }] },
  { id: "dossier-relationnel", label: "Dossier relationnel", definition: "Dossier existant qui rassemble le contexte et les échanges autorisés d’une relation.", category: "Relation", searchAliases: ["dossier de relation", "conversation relationnelle"], relatedTermIds: ["dossier", "acces-candidat"], targets: [{ dataBoussoleId: "relational-cases-workspace-attachment", routes: ["/gouvernance"] }] },
  { id: "acces-candidat", label: "Accès candidat", definition: "Accès limité permettant à une personne autorisée de consulter son dossier selon les règles applicables.", category: "Confiance", searchAliases: ["accès du répondant", "accès privé candidat"], relatedTermIds: ["dossier-relationnel", "validation-humaine"], targets: [{ dataBoussoleId: "candidate-access-controls", routes: ["/cases/:caseId"] }] },
  { id: "objet", label: "Objet", definition: "Élément organisé dans Goodissima, par exemple un Workspace, un parcours, un lien, un dossier ou une communication.", category: "Gouvernance", searchAliases: ["objet métier", "élément"], relatedTermIds: ["workspace", "portfolio"], targets: [{ dataBoussoleId: "portfolio-objects-count", routes: ["/gouvernance/portfolios"] }] },
  { id: "objectif", label: "Objectif", definition: "Résultat principal attendu à la fin d’un parcours.", category: "Gouvernance", searchAliases: ["but", "finalité"], relatedTermIds: ["parcours-gouverne", "resultat-attendu"], targets: [{ dataBoussoleId: "governed-journey-objective", routes: ["/gouvernance/nouveau"] }] },
  { id: "contexte", label: "Contexte", definition: "Informations nécessaires pour comprendre la situation organisée, sans donnée sensible superflue.", category: "Gouvernance", searchAliases: ["situation", "cadre"], relatedTermIds: ["objectif", "contexte-de-travail"], targets: [{ dataBoussoleId: "governed-journey-ai-need", routes: ["/gouvernance/nouveau"] }] },
  { id: "responsabilite", label: "Responsabilité", definition: "Intervention ou décision attendue d’une personne dans un parcours gouverné.", category: "Gouvernance", searchAliases: ["responsable", "mission"], relatedTermIds: ["participant", "etape-de-parcours"], targets: [{ dataBoussoleId: "governed-journey-first-actions", routes: ["/gouvernance/nouveau"] }] },
  { id: "resultat-attendu", label: "Résultat attendu", definition: "Élément qui doit être obtenu ou vérifié pour considérer un objectif ou une étape comme satisfait.", category: "Gouvernance", searchAliases: ["résultat", "condition de réussite"], relatedTermIds: ["objectif", "etape-de-parcours"], targets: [{ dataBoussoleId: "governed-journey-objective", routes: ["/gouvernance/nouveau"] }] },
  { id: "assistant-de-parcours", label: "Assistant de parcours", definition: "Assistance qui prépare une proposition de cadrage à relire et corriger avant toute création.", category: "Assistance", searchAliases: ["assistant gouvernance", "IA parcours"], relatedTermIds: ["intelligence-artificielle", "proposition", "validation-humaine"], targets: [{ dataBoussoleId: "governed-journey-ai-assistant", routes: ["/gouvernance/nouveau"] }] },
  { id: "proposition", label: "Proposition", definition: "Cadrage préparé qui reste modifiable et sans effet métier tant qu’il n’est pas validé.", category: "Assistance", searchAliases: ["suggestion", "brouillon proposé"], relatedTermIds: ["assistant-de-parcours", "validation-humaine"], targets: [{ dataBoussoleId: "governed-journey-proposal", routes: ["/gouvernance/nouveau"] }] },
  { id: "document-attendu", label: "Document attendu", definition: "Document identifié comme nécessaire au parcours, sans constituer un fichier déjà demandé ou reçu.", category: "Gouvernance", searchAliases: ["pièce attendue", "document nécessaire"], relatedTermIds: ["parcours-gouverne", "validation-humaine"], targets: [{ dataBoussoleId: "governed-journey-documents-section", routes: ["/gouvernance/nouveau"] }] },
  { id: "perimetre-d-acces", label: "Périmètre d’accès", definition: "Limites prévues pour un accès futur, qui ne devient effectif qu’après une décision humaine.", category: "Confiance", searchAliases: ["portée de l’accès", "limite d’accès"], relatedTermIds: ["acces-gouverne", "validation-humaine"], targets: [{ dataBoussoleId: "governed-journey-confidentiality", routes: ["/gouvernance/nouveau"] }] },
  { id: "archivage", label: "Archivage", definition: "Action manuelle qui retire un élément de l’activité courante sans le supprimer.", example: "Archiver une annonce devenue inactive.", category: "Publication", searchAliases: ["archive", "archiver", "inactif"], relatedTermIds: ["annonce"], targets: [{ dataBoussoleId: "dashboard-link-archive", routes: ["/dashboard"] }, { dataBoussoleId: "open-archives", routes: ["/opportunities"] }] },
  { id: "statut", label: "Statut", definition: "État visible qui situe une opportunité dans son cycle de vie.", example: "Une annonce peut être active, clôturée ou archivée.", category: "Publication", searchAliases: ["état", "avancement"], relatedTermIds: ["cycle-de-vie", "cloture", "archivage"], targets: [{ dataBoussoleId: "opportunity-card-status", routes: ["/opportunities"] }] },
  { id: "priorite", label: "Priorité", definition: "Niveau utilisé pour organiser le traitement humain d’une situation.", category: "Gouvernance", searchAliases: ["prioritaire", "importance"], relatedTermIds: ["urgence", "validation-humaine"], targets: [] },
  { id: "urgence", label: "Urgence", definition: "Indication qu’une situation mérite une attention rapide sans déclencher d’action automatique.", category: "Gouvernance", searchAliases: ["urgent", "urgente"], relatedTermIds: ["priorite", "validation-humaine"], targets: [] },
  { id: "cloture", label: "Clôture", definition: "État d’une opportunité terminée pour le traitement actif, dont l’historique reste consultable.", category: "Publication", searchAliases: ["clôturée", "fermeture", "terminée"], relatedTermIds: ["statut", "cycle-de-vie"], targets: [{ dataBoussoleId: "opportunity-status-closed", routes: ["/opportunities"] }] },
  { id: "cycle-de-vie", label: "Cycle de vie", definition: "Suite des états traversés par une opportunité, de sa préparation à sa clôture ou son archivage.", category: "Publication", searchAliases: ["lifecycle", "étapes de vie"], relatedTermIds: ["statut", "cloture", "archivage"], targets: [{ dataBoussoleId: "opportunities-summary", routes: ["/opportunities"] }] },
  { id: "suite-a-decider", label: "Suite à décider", definition: "État indiquant qu’une correspondance intéressante attend encore une décision humaine.", category: "Relation", searchAliases: ["décision à prendre", "suivi à décider"], relatedTermIds: ["correspondance-potentielle", "validation-humaine"], targets: [{ dataBoussoleId: "opportunity-matching-status", routes: ["/opportunities"] }] },
  { id: "partage", label: "Partage", definition: "Transmission volontaire d’un lien par son propriétaire après vérification du destinataire.", category: "Publication", searchAliases: ["partager", "transmettre"], relatedTermIds: ["lien-public", "validation-humaine"], targets: [{ dataBoussoleId: "share-opportunity", routes: ["/opportunities"] }] },
  { id: "annonce-publique", label: "Annonce publique", definition: "Vue d’une annonce accessible depuis son lien public ou sécurisé.", category: "Publication", searchAliases: ["vue publique", "publication publique"], relatedTermIds: ["annonce", "lien-public"], targets: [{ dataBoussoleId: "view-public-opportunity", routes: ["/opportunities"] }] },
  { id: "communication-securisee", label: "Communication sécurisée", definition: "Échange rattaché à une relation autorisée et à son contexte.", example: "Rejoindre une salle depuis un dossier autorisé.", category: "Relation", searchAliases: ["message", "conversation sécurisée", "visio"], relatedTermIds: ["dossier", "parcours-gouverne"], targets: [{ dataBoussoleId: "join-secure-communication", routes: ["/cases/:caseId"] }] },
  { id: "boussole", label: "Boussole", definition: "Aide contextuelle locale qui explique la page sans exécuter d’action métier.", example: "Montrer une zone ou rechercher un concept.", category: "Assistance", searchAliases: ["aide", "guide", "glossaire"], relatedTermIds: ["dashboard"], targets: [{ dataBoussoleId: "open-dashboard", routes: ["/boussole", "/dashboard"] }] },
  { id: "modele", label: "Modèle", definition: "Structure de départ réutilisable dont tous les champs restent modifiables.", example: "Importer un modèle de recherche de logement.", category: "Publication", searchAliases: ["template", "bibliothèque", "formulaire prêt"], relatedTermIds: ["lien-simple", "champ"], targets: [{ dataBoussoleId: "choose-simple-link-template", routes: ["/links/simple"] }] },
  { id: "formulaire", label: "Formulaire", definition: "Ensemble structuré de champs présenté à une personne pour recueillir sa réponse.", category: "Publication", searchAliases: ["questions", "collecte", "réponse"], relatedTermIds: ["champ", "lien-securise"], targets: [{ dataBoussoleId: "simple-link-fields", routes: ["/links/simple"] }] },
  { id: "apercu", label: "Aperçu", definition: "Représentation immédiate du formulaire public en cours de préparation.", example: "Vérifier le libellé et l’ordre des champs avant création.", category: "Publication", searchAliases: ["prévisualisation", "preview", "aperçu live"], relatedTermIds: ["formulaire", "validation-humaine"], targets: [{ dataBoussoleId: "simple-link-live-preview", routes: ["/links/simple"] }] },
  { id: "champ", label: "Champ", definition: "Information précise demandée dans un formulaire.", example: "Nom, date, budget ou document.", category: "Publication", searchAliases: ["question", "information demandée"], relatedTermIds: ["type-de-champ", "champ-obligatoire", "formulaire", "section-de-formulaire"], targets: [{ dataBoussoleId: "simple-link-fields", routes: ["/links/simple"] }] },
  { id: "type-de-champ", label: "Type de champ", definition: "Format utilisé pour saisir et contrôler une réponse.", example: "Texte, nombre, date, choix ou fichier.", category: "Publication", searchAliases: ["format de champ", "type de réponse"], relatedTermIds: ["champ", "regle"], targets: [{ dataBoussoleId: "simple-link-field-type", routes: ["/links/simple"] }] },
  { id: "champ-obligatoire", label: "Champ obligatoire", definition: "Champ qui doit être renseigné avant l’envoi du formulaire.", category: "Publication", searchAliases: ["requis", "required", "obligatoire"], relatedTermIds: ["champ", "validation-humaine"], targets: [{ dataBoussoleId: "simple-link-field-required", routes: ["/links/simple"] }] },
  { id: "section-de-formulaire", label: "Section de formulaire", definition: "Regroupement visuel de plusieurs champs autour d’un même thème. Une section ne collecte pas elle-même de réponse.", example: "La section « Coordonnées » peut contenir les champs Nom, Email et Téléphone.", category: "Publication", searchAliases: ["section", "groupe de champs", "organiser le formulaire", "partie du formulaire", "titre de groupe"], relatedTermIds: ["champ", "formulaire", "type-de-champ"], targets: [{ dataBoussoleId: "add-simple-link-section", routes: ["/links/simple"] }] },
  { id: "regle", label: "Règle", definition: "Contrôle associé à un champ pour préciser une valeur ou un format attendu.", example: "Un budget maximum ou une longueur minimale.", category: "Publication", searchAliases: ["règle de validation", "contrôle"], relatedTermIds: ["critere", "regle-indicative", "regle-bloquante"], targets: [{ dataBoussoleId: "add-simple-link-rule", routes: ["/links/simple"] }] },
  { id: "regle-indicative", label: "Règle indicative", definition: "Règle qui signale un écart sans empêcher l’envoi.", category: "Publication", searchAliases: ["indicative", "non bloquante"], relatedTermIds: ["regle", "ecart-a-examiner"], targets: [{ dataBoussoleId: "simple-link-rule-mode", routes: ["/links/simple"] }] },
  { id: "regle-bloquante", label: "Règle bloquante", definition: "Règle qui empêche l’envoi tant que la condition n’est pas respectée.", category: "Publication", searchAliases: ["bloquante", "blocage"], relatedTermIds: ["regle", "critere"], targets: [{ dataBoussoleId: "simple-link-rule-mode", routes: ["/links/simple"] }] },
  { id: "critere", label: "Critère", definition: "Condition explicite utilisée pour apprécier une réponse ou une compatibilité.", category: "Relation", searchAliases: ["condition", "valeur attendue"], relatedTermIds: ["regle", "matching-relationnel"], targets: [{ dataBoussoleId: "simple-link-rule-value", routes: ["/links/simple"] }] },
  { id: "ecart-a-examiner", label: "Écart à examiner", definition: "Différence signalée par une règle indicative qui appelle une lecture humaine.", category: "Relation", searchAliases: ["écart", "signal indicatif"], relatedTermIds: ["regle-indicative", "validation-humaine"], targets: [{ dataBoussoleId: "simple-link-rule-summary", routes: ["/links/simple"] }] },
  { id: "matching-du-lien", label: "Matching du lien", definition: "Comparaison du besoin porté par un lien avec des opportunités existantes, avant tout dossier candidat.", category: "Relation", searchAliases: ["pré-matching", "matching lien"], relatedTermIds: ["matching-relationnel", "correspondance-potentielle"], targets: [{ dataBoussoleId: "enable-link-matching", routes: ["/links/simple"] }] },
  { id: "validation-humaine", label: "Validation humaine", definition: "Vérification et décision réalisées explicitement par une personne.", category: "Confiance", searchAliases: ["confirmation humaine", "contrôle humain"], relatedTermIds: ["boussole", "publication"], targets: [{ dataBoussoleId: "confirm-simple-link", routes: ["/links/simple"] }] },
  { id: "publication", label: "Publication", definition: "Création d’un accès public à un contenu après confirmation explicite.", category: "Publication", searchAliases: ["publier", "mise en ligne"], relatedTermIds: ["annonce", "lien-public", "validation-humaine"], targets: [{ dataBoussoleId: "create-simple-link", routes: ["/links/simple"] }] },
  { id: "lien-public", label: "Lien public", definition: "Adresse que son propriétaire peut transmettre pour ouvrir le formulaire publié.", category: "Publication", searchAliases: ["url", "adresse publique"], relatedTermIds: ["lien-securise", "publication"], targets: [{ dataBoussoleId: "copy-public-link", routes: ["/links/simple"] }, { dataBoussoleId: "copy-opportunity-link", routes: ["/opportunities"] }] },
  { id: "intelligence-artificielle", label: "Assistance par intelligence artificielle", definition: "Fonction qui propose ou explique des éléments à partir des informations fournies. Dans Goodissima, ses propositions doivent toujours être examinées et validées humainement.", example: "L’IA peut proposer des champs pour un formulaire, mais elle ne crée pas le lien automatiquement.", category: "Assistance", searchAliases: ["IA", "intelligence artificielle", "assistant IA", "proposer des champs"], relatedTermIds: ["champ", "validation-humaine"], targets: [{ dataBoussoleId: "suggest-fields-with-ai", routes: ["/links/simple"] }] },
] as const;

export function normalizeGlossarySearch(value: string) {
  return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("fr").trim();
}

export function searchGlossary(query: string) {
  const normalized = normalizeGlossarySearch(query);
  if (!normalized) return [...boussoleGlossary];
  return boussoleGlossary.filter((term) => normalizeGlossarySearch([term.label, term.definition, term.example ?? "", term.category, ...term.searchAliases].join(" ")).includes(normalized));
}

export function getGlossaryTerm(id: string) { return boussoleGlossary.find((term) => term.id === id); }

export function validateGlossaryReferences(glossaryTermIds: string[]) {
  const errors: string[] = [];
  const ids = new Set<string>();
  const labels = new Set<string>();
  for (const term of boussoleGlossary) {
    if (ids.has(term.id)) errors.push(`Identifiant dupliqué : ${term.id}`);
    ids.add(term.id);
    const label = normalizeGlossarySearch(term.label);
    if (labels.has(label)) errors.push(`Terme défini deux fois : ${term.label}`);
    labels.add(label);
  }
  for (const term of boussoleGlossary) for (const relatedId of term.relatedTermIds) if (!ids.has(relatedId)) errors.push(`Terme associé inconnu : ${term.id} -> ${relatedId}`);
  for (const id of glossaryTermIds) if (!ids.has(id)) errors.push(`Référence Guide inconnue : ${id}`);
  return errors;
}
