"use client";

import { useFormState, useFormStatus } from "react-dom";
import { initialGovernedMemoryTransitionActionState, revokeJourneyMemoryRoleAction } from "@/lib/governed-memory/cockpit-transition-actions";

type Role = { beneficiaryKey: string; displayName: string; roleLabel: string; requestKey: string };
function RevokeButton() { const { pending } = useFormStatus(); return <button type="submit" disabled={pending} className="rounded-lg border border-red-300 px-3 py-2 text-sm font-bold text-red-800 disabled:cursor-wait disabled:opacity-60">{pending ? "Révocation…" : "Révoquer la fonction"}</button>; }
function RoleCard({ formTemplateId, role }: { formTemplateId: string; role: Role }) { const [state, action] = useFormState(revokeJourneyMemoryRoleAction, initialGovernedMemoryTransitionActionState); return <li className="rounded-lg border border-slate-200 bg-white p-4"><p className="font-bold text-slate-950">{role.displayName}</p><p className="mt-1 text-sm text-slate-600">{role.roleLabel} · Active</p><details className="mt-3"><summary className="cursor-pointer text-sm font-bold text-red-800">Révoquer cette fonction</summary><div className="mt-3 rounded-lg bg-red-50 p-3"><p className="text-sm text-red-950">La révocation empêchera cette personne d’effectuer de nouvelles qualifications de mémoire pour ce parcours. Les actions historiques déjà réalisées resteront conservées.</p><form action={action} className="mt-3"><input type="hidden" name="formTemplateId" value={formTemplateId} /><input type="hidden" name="beneficiaryKey" value={role.beneficiaryKey} /><input type="hidden" name="requestKey" value={role.requestKey} /><RevokeButton /></form>{state.status !== "IDLE" ? <p role={state.status === "ERROR" ? "alert" : "status"} className="mt-3 text-sm">{state.message}</p> : null}</div></details></li>; }
export function GovernedMemoryRolesPanel({ formTemplateId, roles }: { formTemplateId: string; roles: Role[] }) { return <section className="mt-6 rounded-lg border border-cyan-200 bg-cyan-50/40 p-5"><h2 className="text-lg font-bold text-slate-950">Fonctions mémoire</h2><p className="mt-2 text-sm text-slate-700">Les fonctions mémoire déterminent qui peut établir les faits, ouvrir des contestations et valider les décisions de ce parcours.</p><p className="mt-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950">L’attribution d’une nouvelle fonction n’est pas encore disponible dans ce cockpit : aucun sélecteur d’utilisateur applicatif suffisamment sûr n’existe. Aucun identifiant libre n’est accepté.</p>{roles.length ? <ul className="mt-4 grid gap-3 sm:grid-cols-2">{roles.map((role) => <RoleCard key={role.beneficiaryKey} formTemplateId={formTemplateId} role={role} />)}</ul> : <p className="mt-4 text-sm text-slate-600">Aucune fonction mémoire active.</p>}</section>; }
