"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { CopyLinkButton } from "@/components/CopyLinkButton";
import { QRCodeBox } from "@/components/QRCodeBox";
import type { OpportunityCriteriaV1, OpportunityDay, OpportunityType } from "@/lib/opportunities/contracts";

const dayOptions: Array<[OpportunityDay, string]> = [["MONDAY", "Lundi"], ["TUESDAY", "Mardi"], ["WEDNESDAY", "Mercredi"], ["THURSDAY", "Jeudi"], ["FRIDAY", "Vendredi"], ["SATURDAY", "Samedi"], ["SUNDAY", "Dimanche"]];

export function AutonomousOpportunityManager({ id, initialStatus, publicUrl, initialTitle, initialDescription, initialType, initialCriteria, initialExpiresAt }: { id: string; initialStatus: string; publicUrl: string; initialTitle: string; initialDescription: string; initialType: OpportunityType; initialCriteria: OpportunityCriteriaV1; initialExpiresAt: string }) {
  const router = useRouter(); const [status, setStatus] = useState(initialStatus); const [editing, setEditing] = useState(false); const [qr, setQr] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [title, setTitle] = useState(initialTitle); const [description, setDescription] = useState(initialDescription); const [type, setType] = useState(initialType); const [criteria, setCriteria] = useState(initialCriteria); const [expiresAt, setExpiresAt] = useState(initialExpiresAt);
  const active = status === "ACTIVE";

  async function mutate(action: string, payload: Record<string, unknown> = {}) {
    setBusy(true); setError("");
    try { const response = await fetch(`/api/opportunities/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "Action impossible."); if (typeof body.status === "string") setStatus(body.status); setEditing(false); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Action impossible."); } finally { setBusy(false); }
  }
  function confirmAction(action: string, message: string) { if (window.confirm(message)) void mutate(action); }
  async function share() { if (navigator.share) await navigator.share({ title, url: publicUrl }); else await navigator.clipboard.writeText(publicUrl); }
  function setAvailability(key: "timeFrom" | "timeTo", value: string) { setCriteria({ ...criteria, availability: { ...criteria.availability, [key]: value || undefined } }); }

  return <section data-boussole-id="autonomous-opportunity-publication" className="mt-8 rounded-3xl border bg-white p-5 sm:p-7">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Publication</h2><p className="mt-1 text-sm text-slate-600">{active ? "Publiée — lien public actif." : status === "DISABLED" ? "Publication suspendue." : "Cette opportunité n’est pas encore visible publiquement."}</p></div>
      <details className="relative"><summary className="min-h-11 cursor-pointer list-none rounded-xl border px-4 py-2 font-bold" aria-label="Actions supplémentaires">•••</summary><div className="absolute right-0 z-10 mt-2 flex w-64 flex-col gap-1 rounded-xl border bg-white p-2 shadow-lg"><button className="min-h-11 rounded-lg px-3 text-left hover:bg-slate-50" onClick={() => setEditing(true)}>Modifier</button>{active ? <button className="min-h-11 rounded-lg px-3 text-left hover:bg-slate-50" onClick={() => confirmAction("suspend", "Suspendre la publication de cette opportunité ?")}>Suspendre la publication</button> : null}{status === "DISABLED" ? <button className="min-h-11 rounded-lg px-3 text-left hover:bg-slate-50" onClick={() => confirmAction("resume", "Reprendre la publication de cette opportunité ?")}>Reprendre la publication</button> : null}<button className="min-h-11 rounded-lg px-3 text-left text-red-700 hover:bg-red-50" onClick={() => confirmAction("archive", "Archiver cette opportunité ? Cette action est définitive.")}>Archiver</button></div></details>
    </div>
    {status === "DRAFT" ? <button data-boussole-id="publish-autonomous-opportunity" disabled={busy} onClick={() => confirmAction("publish", "Publier cette opportunité ? Elle deviendra accessible via son lien public et son QR Code.")} className="mt-5 min-h-12 rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white disabled:opacity-50">Publier l’opportunité</button> : null}
    {active ? <div data-boussole-id="autonomous-opportunity-public-link" className="mt-5"><p className="break-all rounded-xl bg-slate-50 p-3 text-sm">{publicUrl}</p><div className="mt-3 flex flex-wrap gap-2"><CopyLinkButton value={publicUrl} /><button className="min-h-11 rounded-xl border px-4 py-2 text-sm font-semibold" aria-expanded={qr} onClick={() => setQr(value => !value)}>QR Code</button><button className="min-h-11 rounded-xl border px-4 py-2 text-sm font-semibold" onClick={() => void share()}>Partager</button></div>{qr ? <div className="mt-4"><QRCodeBox value={publicUrl} fileName={`goodissima-opportunity-${id}.png`} /></div> : null}</div> : null}
    {editing ? <form className="mt-6 space-y-4 border-t pt-6" onSubmit={(event) => { event.preventDefault(); void mutate("update", { title, description, type, criteria, expiresAt: expiresAt || null }); }}><h3 className="font-bold">Modifier l’opportunité</h3><label className="block text-sm font-semibold">Titre<input value={title} onChange={event => setTitle(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="block text-sm font-semibold">Description<textarea value={description} onChange={event => setDescription(event.target.value)} className="mt-1 min-h-28 w-full rounded-xl border px-3 py-2" /></label>
      {status === "DRAFT" ? <><fieldset><legend className="text-sm font-semibold">Type</legend><div className="mt-2 flex gap-4">{(["NEED", "OFFER"] as const).map(value => <label key={value}><input type="radio" checked={type === value} onChange={() => setType(value)} /> {value === "NEED" ? "Je recherche" : "Je propose"}</label>)}</div></fieldset><label className="block text-sm font-semibold">Sujet<input value={criteria.subject} onChange={event => setCriteria({ ...criteria, subject: event.target.value })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="block text-sm font-semibold">Catégorie<input value={criteria.category ?? ""} onChange={event => setCriteria({ ...criteria, category: event.target.value || undefined })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="block text-sm font-semibold">Localisations<input value={criteria.locations?.join(", ") ?? ""} onChange={event => setCriteria({ ...criteria, locations: event.target.value.split(",").map(value => value.trim()).filter(Boolean) })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><fieldset><legend className="text-sm font-semibold">Jours</legend><div className="mt-2 flex flex-wrap gap-3">{dayOptions.map(([day, label]) => <label key={day}><input type="checkbox" checked={criteria.availability?.days?.includes(day) ?? false} onChange={event => setCriteria({ ...criteria, availability: { ...criteria.availability, days: event.target.checked ? [...(criteria.availability?.days ?? []), day] : criteria.availability?.days?.filter(value => value !== day) } })} /> {label}</label>)}</div></fieldset><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Heure de début<input type="time" value={criteria.availability?.timeFrom ?? ""} onChange={event => setAvailability("timeFrom", event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-sm font-semibold">Heure de fin<input type="time" value={criteria.availability?.timeTo ?? ""} onChange={event => setAvailability("timeTo", event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></div><label className="block text-sm font-semibold">Expiration<input type="date" value={expiresAt} onChange={event => setExpiresAt(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></> : <p className="text-sm text-slate-600">Après publication, seuls le titre et la description sont modifiables afin de préserver la stabilité des critères diffusés.</p>}
      {status === "DRAFT" ? <><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Date de début<input type="date" value={criteria.dateWindow?.from ?? ""} onChange={event => setCriteria({ ...criteria, dateWindow: { ...criteria.dateWindow, from: event.target.value || undefined } })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-sm font-semibold">Date de fin<input type="date" value={criteria.dateWindow?.to ?? ""} onChange={event => setCriteria({ ...criteria, dateWindow: { ...criteria.dateWindow, to: event.target.value || undefined } })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></div><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold">Prix minimum<input type="number" min="0" value={criteria.priceRange?.min ?? ""} onChange={event => setCriteria({ ...criteria, priceRange: { ...criteria.priceRange, currency: criteria.priceRange?.currency ?? "EUR", min: event.target.value ? Number(event.target.value) : undefined } })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-sm font-semibold">Prix maximum<input type="number" min="0" value={criteria.priceRange?.max ?? ""} onChange={event => setCriteria({ ...criteria, priceRange: { ...criteria.priceRange, currency: criteria.priceRange?.currency ?? "EUR", max: event.target.value ? Number(event.target.value) : undefined } })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-sm font-semibold">Devise<input maxLength={3} value={criteria.priceRange?.currency ?? ""} onChange={event => setCriteria({ ...criteria, priceRange: event.target.value ? { ...criteria.priceRange, currency: event.target.value.toUpperCase() } : undefined })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></div><label className="block text-sm font-semibold">Critères complémentaires<input value={criteria.terms?.join(", ") ?? ""} onChange={event => setCriteria({ ...criteria, terms: event.target.value.split(",").map(value => value.trim()).filter(Boolean) })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></> : null}
      <div className="flex flex-wrap gap-2"><button disabled={busy} className="min-h-11 rounded-xl bg-slate-900 px-4 py-2 font-semibold text-white">Enregistrer</button><button type="button" className="min-h-11 rounded-xl border px-4 py-2" onClick={() => setEditing(false)}>Annuler</button></div></form> : null}
    {error ? <p role="alert" className="mt-4 text-sm font-semibold text-red-700">{error}</p> : null}
  </section>;
}
