"use client";

import { useEffect, useId, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useRouter } from "next/navigation";
import { CopyLinkButton } from "@/components/CopyLinkButton";
import { QRCodeBox } from "@/components/QRCodeBox";
import type { OpportunityCriteriaV1, OpportunityDay, OpportunityType } from "@/lib/opportunities/contracts";

const dayOptions: Array<[OpportunityDay, string]> = [["MONDAY", "Lundi"], ["TUESDAY", "Mardi"], ["WEDNESDAY", "Mercredi"], ["THURSDAY", "Jeudi"], ["FRIDAY", "Vendredi"], ["SATURDAY", "Samedi"], ["SUNDAY", "Dimanche"]];
type Confirmation = { action: "publish" | "suspend" | "resume" | "archive"; title: string; text: string; cta: string };

export function AutonomousOpportunityManager({ id, initialStatus, publicUrl, initialTitle, initialDescription, initialType, initialCriteria, initialExpiresAt }: { id: string; initialStatus: string; publicUrl: string; initialTitle: string; initialDescription: string; initialType: OpportunityType; initialCriteria: OpportunityCriteriaV1; initialExpiresAt: string }) {
  const router = useRouter(); const [status, setStatus] = useState(initialStatus); const [editing, setEditing] = useState(false); const [qr, setQr] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const dialogId = useId(); const dialog = useRef<HTMLDivElement>(null); const confirmationTrigger = useRef<HTMLButtonElement | null>(null); const [confirmation, setConfirmation] = useState<Confirmation | null>(null);
  const [title, setTitle] = useState(initialTitle); const [description, setDescription] = useState(initialDescription); const [type, setType] = useState(initialType); const [criteria, setCriteria] = useState(initialCriteria); const [expiresAt, setExpiresAt] = useState(initialExpiresAt);
  const active = status === "ACTIVE";

  async function mutate(action: string, payload: Record<string, unknown> = {}) {
    setBusy(true); setError("");
    try { const response = await fetch(`/api/opportunities/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "Action impossible."); if (typeof body.status === "string") setStatus(body.status); setEditing(false); router.refresh(); return true; }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Action impossible."); return false; } finally { setBusy(false); }
  }
  function openConfirmation(value: Confirmation, trigger: HTMLButtonElement) { confirmationTrigger.current = trigger; setConfirmation(value); }
  function closeConfirmation() { setConfirmation(null); requestAnimationFrame(() => confirmationTrigger.current?.focus()); }
  useEffect(() => { if (confirmation) requestAnimationFrame(() => dialog.current?.querySelector<HTMLElement>("button")?.focus()); }, [confirmation]);
  async function share() { if (navigator.share) await navigator.share({ title, url: publicUrl }); else await navigator.clipboard.writeText(publicUrl); }
  function setAvailability(key: "timeFrom" | "timeTo", value: string) { setCriteria({ ...criteria, availability: { ...criteria.availability, [key]: value || undefined } }); }

  return <><section data-boussole-id="autonomous-opportunity-publication" className="mt-8 rounded-3xl border bg-white p-5 sm:p-7">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Publication</h2><p className="mt-1 text-sm text-slate-600">{active ? "Publiée — lien public actif." : status === "DISABLED" ? "Publication suspendue." : "Cette opportunité n’est pas encore visible publiquement."}</p></div>
      <details className="relative"><summary className="min-h-11 cursor-pointer list-none rounded-xl border px-4 py-2 font-bold" aria-label="Actions supplémentaires">•••</summary><div className="absolute right-0 z-10 mt-2 flex w-64 max-w-[calc(100vw-2rem)] flex-col gap-1 rounded-xl border bg-white p-2 shadow-lg"><button className="min-h-11 rounded-lg px-3 text-left hover:bg-slate-50" onClick={() => setEditing(true)}>Modifier</button>{active ? <button className="min-h-11 rounded-lg px-3 text-left hover:bg-slate-50" onClick={event => openConfirmation({ action: "suspend", title: "Suspendre la publication ?", text: "L’opportunité ne sera plus accessible publiquement tant que vous ne la reprendrez pas.", cta: "Suspendre" }, event.currentTarget)}>Suspendre la publication</button> : null}{status === "DISABLED" ? <button className="min-h-11 rounded-lg px-3 text-left hover:bg-slate-50" onClick={event => openConfirmation({ action: "resume", title: "Reprendre la publication ?", text: "L’opportunité redeviendra accessible via son lien public et son QR Code.", cta: "Reprendre" }, event.currentTarget)}>Reprendre la publication</button> : null}<button className="min-h-11 rounded-lg px-3 text-left text-red-700 hover:bg-red-50" onClick={event => openConfirmation({ action: "archive", title: "Archiver cette opportunité ?", text: "Elle ne sera plus accessible publiquement. Cette action ne supprime pas son historique.", cta: "Archiver" }, event.currentTarget)}>Archiver</button></div></details>
    </div>
    {status === "DRAFT" ? <button data-boussole-id="publish-autonomous-opportunity" disabled={busy} onClick={event => openConfirmation({ action: "publish", title: "Publier cette opportunité ?", text: "Elle deviendra accessible via son lien public et son QR Code.", cta: "Publier" }, event.currentTarget)} className="mt-5 min-h-12 rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white disabled:opacity-50">Publier l’opportunité</button> : null}
    {active ? <div data-boussole-id="autonomous-opportunity-public-link" className="mt-5"><p className="break-all rounded-xl bg-slate-50 p-3 text-sm">{publicUrl}</p><div className="mt-3 flex flex-wrap gap-2"><CopyLinkButton value={publicUrl} /><button className="min-h-11 rounded-xl border px-4 py-2 text-sm font-semibold" aria-expanded={qr} onClick={() => setQr(value => !value)}>QR Code</button><button className="min-h-11 rounded-xl border px-4 py-2 text-sm font-semibold" onClick={() => void share()}>Partager</button></div>{qr ? <div className="mt-4"><QRCodeBox value={publicUrl} fileName={`goodissima-opportunity-${id}.png`} /></div> : null}</div> : null}
    {editing ? <form className="mt-6 space-y-4 border-t pt-6" onSubmit={(event) => { event.preventDefault(); void mutate("update", { title, description, type, criteria, expiresAt: expiresAt || null }); }}><h3 className="font-bold">Modifier l’opportunité</h3><label className="block text-sm font-semibold">Titre<input value={title} onChange={event => setTitle(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="block text-sm font-semibold">Description<textarea value={description} onChange={event => setDescription(event.target.value)} className="mt-1 min-h-28 w-full rounded-xl border px-3 py-2" /></label>
      {status === "DRAFT" ? <><fieldset><legend className="text-sm font-semibold">Type</legend><div className="mt-2 flex gap-4">{(["NEED", "OFFER"] as const).map(value => <label key={value}><input type="radio" checked={type === value} onChange={() => setType(value)} /> {value === "NEED" ? "Je recherche" : "Je propose"}</label>)}</div></fieldset><label className="block text-sm font-semibold">Sujet<input value={criteria.subject} onChange={event => setCriteria({ ...criteria, subject: event.target.value })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="block text-sm font-semibold">Catégorie<input value={criteria.category ?? ""} onChange={event => setCriteria({ ...criteria, category: event.target.value || undefined })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="block text-sm font-semibold">Localisations<input value={criteria.locations?.join(", ") ?? ""} onChange={event => setCriteria({ ...criteria, locations: event.target.value.split(",").map(value => value.trim()).filter(Boolean) })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><fieldset><legend className="text-sm font-semibold">Jours</legend><div className="mt-2 flex flex-wrap gap-3">{dayOptions.map(([day, label]) => <label key={day}><input type="checkbox" checked={criteria.availability?.days?.includes(day) ?? false} onChange={event => setCriteria({ ...criteria, availability: { ...criteria.availability, days: event.target.checked ? [...(criteria.availability?.days ?? []), day] : criteria.availability?.days?.filter(value => value !== day) } })} /> {label}</label>)}</div></fieldset><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Heure de début<input type="time" value={criteria.availability?.timeFrom ?? ""} onChange={event => setAvailability("timeFrom", event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-sm font-semibold">Heure de fin<input type="time" value={criteria.availability?.timeTo ?? ""} onChange={event => setAvailability("timeTo", event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></div><label className="block text-sm font-semibold">Expiration<input type="date" value={expiresAt} onChange={event => setExpiresAt(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></> : <p className="text-sm text-slate-600">Après publication, seuls le titre et la description sont modifiables afin de préserver la stabilité des critères diffusés.</p>}
      {status === "DRAFT" ? <><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Date de début<input type="date" value={criteria.dateWindow?.from ?? ""} onChange={event => setCriteria({ ...criteria, dateWindow: { ...criteria.dateWindow, from: event.target.value || undefined } })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-sm font-semibold">Date de fin<input type="date" value={criteria.dateWindow?.to ?? ""} onChange={event => setCriteria({ ...criteria, dateWindow: { ...criteria.dateWindow, to: event.target.value || undefined } })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></div><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold">Prix minimum<input type="number" min="0" value={criteria.priceRange?.min ?? ""} onChange={event => setCriteria({ ...criteria, priceRange: { ...criteria.priceRange, currency: criteria.priceRange?.currency ?? "EUR", min: event.target.value ? Number(event.target.value) : undefined } })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-sm font-semibold">Prix maximum<input type="number" min="0" value={criteria.priceRange?.max ?? ""} onChange={event => setCriteria({ ...criteria, priceRange: { ...criteria.priceRange, currency: criteria.priceRange?.currency ?? "EUR", max: event.target.value ? Number(event.target.value) : undefined } })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-sm font-semibold">Devise<input maxLength={3} value={criteria.priceRange?.currency ?? ""} onChange={event => setCriteria({ ...criteria, priceRange: event.target.value ? { ...criteria.priceRange, currency: event.target.value.toUpperCase() } : undefined })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></div><label className="block text-sm font-semibold">Critères complémentaires<input value={criteria.terms?.join(", ") ?? ""} onChange={event => setCriteria({ ...criteria, terms: event.target.value.split(",").map(value => value.trim()).filter(Boolean) })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></> : null}
      <div className="flex flex-wrap gap-2"><button disabled={busy} className="min-h-11 rounded-xl bg-slate-900 px-4 py-2 font-semibold text-white">Enregistrer</button><button type="button" className="min-h-11 rounded-xl border px-4 py-2" onClick={() => setEditing(false)}>Annuler</button></div></form> : null}
    {error ? <p role="alert" className="mt-4 text-sm font-semibold text-red-700">{error}</p> : null}
  </section>{confirmation ? createPortal(<div className="fixed inset-0 z-[110] flex items-end justify-center bg-slate-950/45 p-3 sm:items-center sm:p-4" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget && !busy) closeConfirmation(); }}><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby={`${dialogId}-title`} aria-describedby={`${dialogId}-description`} className="max-h-[calc(100dvh-1.5rem)] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl sm:p-6" onKeyDown={event => { if (event.key === "Escape" && !busy) { event.preventDefault(); closeConfirmation(); } if (event.key === "Tab") { const nodes = Array.from(dialog.current?.querySelectorAll<HTMLElement>("button:not(:disabled)") ?? []); const first = nodes[0], last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }}><h2 id={`${dialogId}-title`} className="text-lg font-bold text-slate-950">{confirmation.title}</h2><p id={`${dialogId}-description`} className="mt-3 text-sm leading-relaxed text-slate-700">{confirmation.text}</p><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" disabled={busy} onClick={closeConfirmation} className="min-h-11 rounded-xl border px-4 py-2 font-semibold">Annuler</button><button type="button" disabled={busy} onClick={() => void mutate(confirmation.action).then(() => closeConfirmation())} className="min-h-11 rounded-xl bg-slate-900 px-4 py-2 font-semibold text-white disabled:opacity-60">{busy ? "Mise à jour…" : confirmation.cta}</button></div></div></div>, document.body) : null}</>;
}
