"use client";
import { useState } from "react";
import { prepareGovernanceReviewWithAIAssistantAction, type GovernanceReviewAIHelp } from "@/lib/governance-review-ai-actions";
export function GovernanceReviewAIAssistant(props: { formTemplateId: string; reason: string; question: string; humanNote?: string | null }) {
  const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [help, setHelp] = useState<GovernanceReviewAIHelp | null>(null);
  async function run() { setPending(true); setError(null); const result = await prepareGovernanceReviewWithAIAssistantAction(props); setHelp(result.help ?? null); setError(result.error ?? null); setPending(false); }
  const fields: Array<[keyof GovernanceReviewAIHelp, string]> = [["pointsToExamine", "Points à examiner"], ["blockers", "Blocages"], ["questionsToDecide", "Questions à trancher"], ["humanActions", "Actions humaines possibles"], ["limits", "Limites"]];
  return <div className="mt-4 rounded-lg border border-[#b9dfe2] bg-white p-3"><button type="button" onClick={run} disabled={pending} className="rounded-lg bg-[#247f88] px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{pending ? "Préparation…" : "Préparer avec l’assistant"}</button><p className="mt-2 text-xs text-slate-600">L’assistant propose une aide à la préparation. La revue doit être validée par un humain.</p><p className="text-xs text-slate-600">Aucune décision, notification ou réunion n’est déclenchée automatiquement.</p>{error ? <p className="mt-3 rounded-lg bg-amber-50 p-2 text-sm text-amber-900">{error}</p> : null}{help ? <div className="mt-4 space-y-3"><label className="block text-xs font-bold">Synthèse<textarea value={help.summary} onChange={(event) => setHelp({ ...help, summary: event.target.value })} className="mt-1 min-h-28 w-full rounded-lg border p-2 text-sm font-normal" /></label>{fields.map(([key, label]) => <label key={key} className="block text-xs font-bold">{label}<textarea value={(help[key] as string[]).join("\n")} onChange={(event) => setHelp({ ...help, [key]: event.target.value.split("\n") })} className="mt-1 min-h-20 w-full rounded-lg border p-2 text-sm font-normal" /></label>)}<button type="button" onClick={() => navigator.clipboard.writeText([help.summary, ...fields.flatMap(([key, label]) => [label, ...(help[key] as string[])])].join("\n"))} className="rounded-lg border px-3 py-2 text-xs font-bold">Copier l’aide</button></div> : null}</div>;
}
