"use client";

import { useEffect, useId, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useRouter } from "next/navigation";

export function OpportunityMatchingControls({ id, status, initialEnabled }: { id: string; status: string; initialEnabled: boolean }) {
  const router = useRouter(); const dialogId = useId(); const dialog = useRef<HTMLDivElement>(null); const trigger = useRef<HTMLButtonElement>(null);
  const [enabled, setEnabled] = useState(initialEnabled); const [confirmation, setConfirmation] = useState<"enable" | "disable" | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (confirmation) requestAnimationFrame(() => dialog.current?.querySelector<HTMLElement>("button")?.focus()); }, [confirmation]);
  function close() { setConfirmation(null); requestAnimationFrame(() => trigger.current?.focus()); }
  async function update() {
    const next = confirmation === "enable"; setBusy(true); setError("");
    try { const response = await fetch(`/api/opportunities/${encodeURIComponent(id)}/matching`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: next }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "Action impossible."); setEnabled(body.matchingEnabled === true); close(); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Action impossible."); } finally { setBusy(false); }
  }
  if (status === "DRAFT") return null;
  const active = status === "ACTIVE";
  const inactiveText = status === "DISABLED" && enabled ? "Matching autorisé · en pause car l’opportunité est suspendue." : status === "EXPIRED" ? "L’opportunité est expirée." : "L’opportunité est archivée.";
  return <><section className="mt-6 rounded-3xl border bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Matching</h2>{active ? <><p className="mt-2 font-semibold">{enabled ? "Matching activé" : "Matching désactivé"}</p><p className="mt-1 text-sm leading-6 text-slate-600">{enabled ? "Les critères structurés autorisés de cette opportunité peuvent être utilisés pour rechercher des correspondances." : "Goodissima n’utilise pas encore les critères de cette opportunité pour rechercher des correspondances."}</p><button ref={trigger} type="button" disabled={busy} onClick={() => setConfirmation(enabled ? "disable" : "enable")} className="mt-4 min-h-11 rounded-xl border px-4 py-2 font-semibold disabled:opacity-50">{enabled ? "Suspendre le matching" : "Activer le matching"}</button></> : <><p className="mt-2 font-semibold">Matching inactif</p><p className="mt-1 text-sm text-slate-600">{inactiveText}</p>{enabled ? <button ref={trigger} type="button" disabled={busy} onClick={() => setConfirmation("disable")} className="mt-4 min-h-11 rounded-xl border px-4 py-2 font-semibold">Suspendre le matching</button> : null}</>}{error ? <p role="alert" className="mt-4 text-sm font-semibold text-red-700">{error}</p> : null}</section>
    {confirmation ? createPortal(<div className="fixed inset-0 z-[110] flex items-end justify-center bg-slate-950/45 p-3 sm:items-center sm:p-4" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget && !busy) close(); }}><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby={`${dialogId}-title`} aria-describedby={`${dialogId}-description`} className="max-h-[calc(100dvh-1.5rem)] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl sm:p-6" onKeyDown={event => { if (event.key === "Escape" && !busy) { event.preventDefault(); close(); } if (event.key === "Tab") { const nodes = Array.from(dialog.current?.querySelectorAll<HTMLElement>("button:not(:disabled)") ?? []); const first = nodes[0], last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }}><h2 id={`${dialogId}-title`} className="text-lg font-bold">{confirmation === "enable" ? "Activer le matching ?" : "Suspendre le matching ?"}</h2><p id={`${dialogId}-description`} className="mt-3 text-sm leading-relaxed text-slate-700">{confirmation === "enable" ? "Goodissima pourra utiliser les critères structurés de cette opportunité pour rechercher des offres ou besoins compatibles. Vos coordonnées, votre identité privée et vos documents ne sont pas utilisés par le moteur de matching." : active ? "Goodissima cessera d’utiliser cette opportunité pour de nouvelles recherches de correspondances. L’opportunité restera publiée et son lien public restera accessible." : "Goodissima cessera d’utiliser cette opportunité pour de nouvelles recherches de correspondances. Le statut de publication ne sera pas modifié."}</p><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" disabled={busy} onClick={close} className="min-h-11 rounded-xl border px-4 py-2 font-semibold">Annuler</button><button type="button" disabled={busy} onClick={() => void update()} className="min-h-11 rounded-xl bg-slate-900 px-4 py-2 font-semibold text-white disabled:opacity-60">{busy ? "Mise à jour…" : confirmation === "enable" ? "Activer le matching" : "Suspendre"}</button></div></div></div>, document.body) : null}</>;
}
