"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { RelationRequestView } from "@/lib/relation-request-view";
export type { RelationRequestView } from "@/lib/relation-request-view";
const labels = { PENDING: "EN ATTENTE", ACCEPTED: "ACCEPTÉE", DECLINED: "REFUSÉE" } as const;

export function RelationRequestsPanel({ requests, gLinkId }: { requests: RelationRequestView[]; gLinkId: string }) {
  const router = useRouter(); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState(""); const [feedback, setFeedback] = useState(""); const [declining, setDeclining] = useState<string | null>(null); const [reason, setReason] = useState("");
  async function decide(id: string, decision: "accept" | "decline") {
    if (busy) return; if (decision === "decline" && reason.trim().length < 3) { setError("Le motif du refus doit contenir au moins 3 caractères."); return; }
    setBusy(id); setError(""); setFeedback("");
    try { const response = await fetch(`/api/relation-requests/${encodeURIComponent(id)}/${decision}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(decision === "decline" ? { reason: reason.trim(), gLinkId } : { gLinkId }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Cette demande n’est plus disponible."); const base = decision === "accept" ? "Demande acceptée" : "Demande refusée"; setFeedback(result.notificationStatus === "SENT" ? `${base} et demandeur informé par e-mail.` : result.notificationStatus === "FAILED" ? `${base}. La notification e-mail n’a pas pu être délivrée.` : `${base}. Aucun canal e-mail n’avait été autorisé.`); setDeclining(null); setReason(""); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Action impossible."); } finally { setBusy(null); }
  }
  async function openAttachment(id: string, index: number) { const response = await fetch(`/api/relation-requests/${encodeURIComponent(id)}/attachments/${index}`); const result = await response.json(); if (!response.ok || typeof result.signedUrl !== "string") { setError("Cette pièce jointe est indisponible."); return; } window.open(result.signedUrl, "_blank", "noopener,noreferrer"); }
  const format = (value: string) => new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Paris" }).format(new Date(value));
  return <div className="mt-5 space-y-3">{error ? <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}{feedback ? <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{feedback}</p> : null}{requests.map((request) => <article id={`relation-request-${request.id}`} key={request.id} className="scroll-mt-24 rounded-2xl border p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{request.candidateName || "Demandeur"}</h3><p className="mt-1 text-xs text-slate-500">Créée le <time dateTime={request.createdAt}>{format(request.createdAt)}</time></p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{labels[request.status]}</span></div>
    {request.decidedAt ? <p className="mt-2 text-xs text-slate-500">Décidée le <time dateTime={request.decidedAt}>{format(request.decidedAt)}</time></p> : null}{request.status === "DECLINED" ? <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm"><strong>Motif du refus :</strong> {request.declineReason}</p> : null}{request.status === "ACCEPTED" && request.relationCaseId ? <Link href={`/cases/${request.relationCaseId}?refresh=1`} className="mt-3 inline-flex min-h-11 items-center rounded-xl bg-slate-900 px-4 text-sm font-semibold text-white">Ouvrir le dossier</Link> : null}
    <details className="mt-3"><summary className="min-h-11 cursor-pointer py-2 font-semibold text-slate-700">Historique de la demande</summary><ol className="space-y-3 rounded-xl bg-slate-50 p-4 text-sm">{request.history.map((event, index) => <li key={`${event.type}-${event.occurredAt}-${index}`}><p><time dateTime={event.occurredAt}>{format(event.occurredAt)}</time> — {event.label}</p>{event.detail ? <p className="mt-1 text-slate-700"><strong>Motif :</strong> {event.detail}</p> : null}{event.actorLabel ? <p className="mt-1 text-slate-600">{event.actorLabel}</p> : null}</li>)}</ol></details>
    <details className="mt-3" open={request.status === "PENDING"}><summary className="min-h-11 cursor-pointer py-2 font-semibold text-cyan-800">{request.status === "PENDING" ? "Examiner" : "Voir la demande initiale"}</summary><div className="rounded-xl bg-slate-50 p-4 text-sm"><p><strong>Demandeur :</strong> {request.candidateName || "Nom déclaré non renseigné"}</p>{request.message ? <p className="mt-2 whitespace-pre-wrap"><strong>Message :</strong> {request.message}</p> : null}{request.answers.length ? <dl className="mt-3 space-y-2">{request.answers.map((answer) => <div key={answer.label}><dt className="font-semibold">{answer.label}</dt><dd>{answer.value}</dd></div>)}</dl> : null}{request.attachments.length ? <ul className="mt-3">{request.attachments.map((attachment, index) => <li key={`${attachment.fileName}-${index}`}><button type="button" className="min-h-11 font-semibold text-cyan-800 underline" onClick={() => void openAttachment(request.id, index)}>{attachment.fileName}</button></li>)}</ul> : null}<p className="mt-3 font-semibold">{request.notificationAllowed ? "Notification e-mail autorisée" : "Aucun canal e-mail autorisé"}</p>
      {request.status === "PENDING" ? <div className="mt-4"><p>Accepter ouvrira la relation et créera son dossier.</p>{!request.notificationAllowed ? <p className="mt-2 rounded-lg bg-amber-50 p-3">Aucun canal e-mail n’a été autorisé par le demandeur. La décision sera historisée mais ne pourra pas lui être envoyée par e-mail.</p> : null}<div className="mt-3 flex gap-2"><button disabled={Boolean(busy)} onClick={() => void decide(request.id, "accept")} className="min-h-11 rounded-xl bg-slate-900 px-4 font-semibold text-white">Accepter la demande</button><button disabled={Boolean(busy)} onClick={() => setDeclining(request.id)} className="min-h-11 rounded-xl border px-4 font-semibold">Refuser</button></div>{declining === request.id ? <div className="mt-3"><label className="block font-semibold">Motif du refus<textarea required minLength={3} maxLength={500} value={reason} onChange={(event) => setReason(event.target.value)} className="mt-1 min-h-28 w-full rounded-xl border bg-white p-3 font-normal" /></label><p className="mt-2 text-xs">Ce motif sera conservé avec la décision et communiqué au demandeur lorsqu’un canal de notification autorisé existe.</p><button disabled={Boolean(busy) || reason.trim().length < 3} onClick={() => void decide(request.id, "decline")} className="mt-3 min-h-11 rounded-xl bg-red-800 px-4 font-semibold text-white disabled:opacity-50">Confirmer le refus</button></div> : null}</div> : null}</div></details>
  </article>)}</div>;
}
