"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
export type RelationRequestView = { id: string; title: string; candidateName: string };
export function RelationRequestsPanel({ requests }: { requests: RelationRequestView[] }) {
  const router = useRouter(); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState("");
  async function decide(id: string, decision: "accept" | "decline") { if (busy) return; setBusy(id); setError(""); try { const response = await fetch(`/api/relation-requests/${encodeURIComponent(id)}/${decision}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); if (!response.ok) throw new Error("Cette demande n’est plus disponible."); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Action impossible."); } finally { setBusy(null); } }
  return <section className="mt-6 rounded-3xl border bg-white p-6" aria-labelledby="relation-requests-title"><h2 id="relation-requests-title" className="text-xl font-bold">Demandes de relation</h2><p className="mt-2 text-sm text-slate-600">Accepter ouvrira la relation et créera son dossier.</p>{error ? <p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}{requests.length ? <div className="mt-4 space-y-3">{requests.map((request) => <article key={request.id} className="rounded-2xl border p-4"><h3 className="font-semibold">{request.title}</h3><p className="mt-1 text-sm text-slate-600">{request.candidateName || "Demandeur"} · En attente</p><div className="mt-4 flex gap-2"><button disabled={Boolean(busy)} onClick={() => void decide(request.id, "accept")} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Accepter</button><button disabled={Boolean(busy)} onClick={() => void decide(request.id, "decline")} className="rounded-xl border px-4 py-2 text-sm font-semibold disabled:opacity-50">Refuser</button></div></article>)}</div> : <p className="mt-4 text-sm text-slate-500">Aucune demande en attente.</p>}</section>;
}
